<?php 
$pages = Wo_GetCustomPages();
?>
<div class="page-margin">
    <div class="footer-wrapper">
        <div class="footer-powered">
            <ul class="list-inline">
                <li><a href="<?php echo $wo['config']['site_url'];?>" data-ajax="?link1=home"><?php echo $wo['lang']['home'];?></a></li>
                <li><a href="<?php echo Wo_SeoLink('index.php?link1=terms&type=about-us');?>" data-ajax="?link1=terms&type=about-us"><?php echo $wo['lang']['about'];?></a></li>
                <li><a href="<?php echo Wo_SeoLink('index.php?link1=contact-us');?>" data-ajax="?link1=contact-us"><?php echo $wo['lang']['contact_us'];?></a></li>
                <li><a href="<?php echo Wo_SeoLink('index.php?link1=terms&type=privacy-policy');?>" data-ajax="?link1=terms&type=privacy-policy"><?php echo $wo['lang']['privacy_policy'];?></a></li>
                <li><a href="<?php echo Wo_SeoLink('index.php?link1=terms&type=terms');?>" data-ajax="?link1=terms&type=terms"><?php echo $wo['lang']['terms_of_use'];?></a></li>
                <?php if (count($pages) > 0) { ?>
                    <li>
                        <div class="dropdown dropup">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                                <?php echo $wo['lang']['more'];?> <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu" role="menu" style="width: auto; min-width: 100px; font-size: 11px;">
                                <?php
                                    foreach ($pages as $key => $page) {
                                ?>
                                    <li><a href="<?php echo Wo_SeoLink('index.php?link1=site-pages&page_name=' . $page['page_name']);?>"><?php echo $page['page_title'];?></a></li>
                                <?php } ?>
                            </ul>
                        </div>
                    </li> 
                <?php } ?>
            </ul>
            <div class="footer-copyright">
                <p>
                    <?php 
                        $copy = str_replace('{site_name}', $wo['config']['siteName'], $wo['lang']['copyrights']);
                        echo $copy = str_replace('{date}', date('Y'), $copy);
                    ?>
                </p>
            </div>
        </div>
        <div class="clear"></div>
    </div>
</div>
