<?php
$fields = Wo_GetWelcomeFileds();
?>
<!-- // zomo  customization -->
<link href="<?php echo $wo['config']['theme_url'];?>/stylesheet/cropper.min.css" rel="stylesheet">
<script src="<?php echo $wo['config']['theme_url'];?>/javascript/cropper.min.js"></script>
<!-- // zomo  customization end -->

<div class="page-margin">
	<div class="row">
		<div class="col-md-2 leftcol"><?php echo Wo_LoadPage("sidebar/left-sidebar"); ?></div>
		<div class="col-md-7 middlecol">
			<div class="page-margin wow_content mt-0">
				<div class="wo_page_hdng pag_neg_padd pag_alone">
					<div class="wo_page_hdng_innr">
						<span><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24"><path fill="currentColor" d="M19 19V8H5V19H19M16 1H18V3H19C20.11 3 21 3.9 21 5V19C21 20.11 20.11 21 19 21H5C3.89 21 3 20.1 3 19V5C3 3.89 3.89 3 5 3H6V1H8V3H16V1M11 9.5H13V12.5H16V14.5H13V17.5H11V14.5H8V12.5H11V9.5Z"></path></svg></span> <?php echo $wo['lang']['create_events'];?>
					</div>
				</div>
			</div>

			<div class="page-margin wow_content wow_sett_content">
				<form class="form form-horizontal" method="post" id="insert-event">
			

					<div class="wow_form_fields">
						<label for="event-name"><?php echo $wo['lang']['name']; ?></label>
						<input id="event-name" name="event-name" type="text">
					</div>
					<div class="wow_form_fields">
						<label for="event-locat"><?php echo $wo['lang']['location']; ?></label>
						<input id="event-locat" name="event-locat" type="text">
					</div>
					<?php if ($wo['config']['google_map'] == 1 || $wo['config']['yandex_map'] == 1) { ?>
						<div id="review-location">
							<div id="place" <?php echo($wo['config']['yandex_map'] == 1 ? 'class="yandex_ads_map"' : '') ?>></div>
						</div>
					<?php } ?>
					<div class="wow_form_fields">
						<label for="event-start"><?php echo $wo['lang']['event_start']; ?></label>
						<div class="row">
							<div class="col-md-6">
								<input type="text" class="date" id="event-start" name="event-start-date">
							</div>
							<div class="col-md-6">
								<input type="text" id="event-start-time" class="time1" name="event-start-time">
							</div>
						</div>
					</div>
					<div class="wow_form_fields">
						<label for="event-end-date"><?php echo $wo['lang']['event_end']; ?></label>
						<div class="row">
							<div class="col-md-6">
								<input type="text" class="date1" name="event-end-date" id="event-end-date">
							</div>
							<div class="col-md-6">
								<input type="text" id="event-end-time" class="time1" name="event-end-time">
							</div>
						</div>
					</div>
					<div class="wow_form_fields">
						<label for="event-description"><?php echo $wo['lang']['description']; ?></label>
						<textarea name="event-description" id="event-description" rows="5"></textarea>
					</div>
					<div class="wow_form_fields">
						<label><?php echo $wo['lang']['image']; ?></label>
						<div class="wow_fcov_image">
							<div id="wow_fcov_img_holder">
								<img src="<?php echo $wo['config']['theme_url'];?>/img/ad_pattern.png">
							</div>
							<div class="upload_ad_image" onclick="document.getElementById('event-cover').click(); return false">
								<div class="upload_ad_image_content">
									<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24"><path fill="currentColor" d="M8.5,13.5L11,16.5L14.5,12L19,18H5M21,19V5C21,3.89 20.1 3 19,3H5A2,2 0 0,0 3,5V19A2,2 0 0,0 5,21H19A2,2 0 0,0 21,19Z"></path></svg> <?php echo $wo['lang']['choose_image'] ?>
								</div>
							</div>
						</div>
					</div>

					<!-- Hidden input for storing the cropped image data -->
					<input type="hidden" id="cropped_image" name="cropped_image">
					
					<div class="setting-update-alert" id="event-alert"></div>
					
					<div class="text-center">
						<a class="btn btn-mat" href="<?php echo Wo_SeoLink('index.php?link1=my-events'); ?>" data-ajax="?link1=my-events">
							<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24"><path fill="currentColor" d="M20,11V13H8L13.5,18.5L12.08,19.92L4.16,12L12.08,4.08L13.5,5.5L8,11H20Z"></path></svg> <?php echo $wo['lang']['go_back'];?>
						</a>
						<button class="btn btn-main btn-mat btn-mat-raised add_wow_loader" type="submit"><?php echo $wo['lang']['publish']; ?></button>
					</div>
					<input type="hidden" name="hash_id" value="<?php echo Wo_CreateSession();?>">
					<input type="file" name="event-cover" class="hidden" id="event-cover" accept="image/*">


					
				</form>
			</div>
		</div>
		<!-- .col-md-8 -->
		<?php echo Wo_LoadPage('sidebar/content');?>
	</div>
</div>




<!-- // zomo  customization -->
<div class="modal fade" id="cropperModal" role="dialog">
	<div class="modal-dialog wow_mat_mdl">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-x"><line x1="18" y1="6" x2="6" y2="18"></line><line x1="6" y1="6" x2="18" y2="18"></line></svg></span></button>
				<h4 class="modal-title"><?php echo $wo['lang']['crop_image']; ?></h4>
			</div>
			<div class="modal-body">
				<div class="img-container">
          			<img id="image" src="" width="100%">
        		</div>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-secondary" data-dismiss="modal"><?php echo $wo['lang']['cancel']; ?></button>
				<button type="button" class="btn btn-primary" id="cropImage"><?php echo $wo['lang']['crop']; ?></button>
			</div>
		</div>
	</div>
</div>

<!-- // zomo  customization end -->

<script>
	jQuery(document).ready(function($) {

		// zomo  customization
		var cropper;
		var image = document.getElementById('image');
		var input = document.getElementById('event-cover');

		input.addEventListener('change', function(e) {
			var files = e.target.files;
			var done = function(url) {
				image.src = url;
				$('#cropperModal').modal('show');
			};
			var reader;
			var file;
			var url;

			if (files && files.length > 0) {
				file = files[0];

				if (URL) {
					done(URL.createObjectURL(file));
				} else if (FileReader) {
					reader = new FileReader();
					reader.onload = function(e) {
						done(reader.result);
					};
					reader.readAsDataURL(file);
				}
			}
		});

		$('#cropperModal').on('shown.bs.modal', function() {
			cropper = new Cropper(image, {
				aspectRatio: 16 / 9,
				viewMode: 3,
			});
		}).on('hidden.bs.modal', function() {
			cropper.destroy();
			cropper = null;
		});

		document.getElementById('cropImage').addEventListener('click', function() {
			var canvas;
			if (cropper) {
				canvas = cropper.getCroppedCanvas({
					width: 800,
					height: 450,
				});
				canvas.toBlob(function(blob) {
					var reader = new FileReader();
					reader.readAsDataURL(blob);
					reader.onloadend = function() {
						var base64data = reader.result;
						$("#wow_fcov_img_holder").html("<img src='" + base64data + "' alt='Picture'>");
						$('#cropped_image').val(base64data);  // Set the base64 data into the hidden input
						$('#cropperModal').modal('hide');
					};
				});
			}
		});


		// zomo  customization end

		$('#insert-event').ajaxForm({
			url: Wo_Ajax_Requests_File() + '?f=insert-event',
			beforeSend: function() {
				$('#insert-event').find('.add_wow_loader').addClass('btn-loading').prop('disabled', true).off('click');
			},
			success: function(data) {
				if (data['status'] == 200) {
					$("#event-alert").html('<div class="alert alert-success">'+ data['message'] +'</div>');
					window.location = data['url'];
				}
				else if (data['message']) {
					$("#event-alert").html('<div class="alert alert-danger">' + data['message'] + '</div>');
					$('#insert-event').find('.add_wow_loader').removeClass('btn-loading').prop('disabled', false).on('click');
				} 
			}
		});
	});
</script>


<script>
	<?php if ($wo['config']['google_map'] == 1) { ?>

		$(document).ready(function() {

			var input = document.getElementById('event-locat');
			var autocomplete = new google.maps.places.Autocomplete(input);


			autocomplete.addListener('place_changed', function() {
				var place = autocomplete.getPlace();

				if (place.geometry) {

					$("#review-location #place").html('<iframe width="100%" frameborder="0" style="border:0;margin-top: 10px;" src="https://www.google.com/maps/embed/v1/place?key=<?php echo $wo['config']['google_map_api']; ?>&q=' + encodeURIComponent(place.formatted_address) + '&language=en"></iframe>');
				}
			});


			$('#event-locat').on('input', function() {
				if ($(this).val().length >= 3) {

					$("#review-location #place").html('<iframe width="100%" frameborder="0" style="border:0;margin-top: 10px;" src="https://www.google.com/maps/embed/v1/place?key=<?php echo $wo['config']['google_map_api']; ?>&q=' + encodeURIComponent($(this).val()) + '&language=en"></iframe>');
				} else {
					$("#review-location #place").html('<iframe width="100%" frameborder="0" style="border:0;margin-top: 10px;" src="https://www.google.com/maps/embed/v1/place?key=<?php echo $wo['config']['google_map_api']; ?>&q=us&language=en"></iframe>');
				}
			});
		});
     <?php } ?>
     <?php if ($wo['config']['yandex_map'] == 1) { ?>
		 	$(document).on('change', '#event-locat', function(event) {
		   	var myMap;
		    ymaps.geocode($(this).val()).then(function (res) {
		    	$("#review-location #place").html('');
		        myMap = new ymaps.Map('place', {
		            center: res.geoObjects.get(0).geometry.getCoordinates(),
		            zoom : 10
		        });
		        myMap.geoObjects.add(new ymaps.Placemark(res.geoObjects.get(0).geometry.getCoordinates(), {
		            balloonContent: ''
		        }));
		    });
		 	});

		 <?php } ?>
  jQuery(document).ready(function($) {
		$(".date").flatpickr({
			dateFormat: "Y-m-d",
			altInput: true,
			altFormat: "F j, Y",
			minDate: "today",
		});
		
		$(".time1").flatpickr({
			enableTime: true,
			noCalendar: true,
			dateFormat: "H:i",
		});
		
		$(".date1").flatpickr({
			dateFormat: "Y-m-d",
			altInput: true,
			altFormat: "F j, Y",
			minDate: new Date().fp_incr(1),
		});


      $("#event-cover").change(function(event) {
        $("#wow_fcov_img_holder").html("<img src='" + window.URL.createObjectURL(this.files[0]) + "' alt='Picture'>")
      });

      $('#insert-event').ajaxForm({
            url: Wo_Ajax_Requests_File() + '?f=insert-event',
            beforeSend: function() {
              $('#insert-event').find('.add_wow_loader').addClass('btn-loading').prop('disabled', true).off('click');
            },
            success: function(data) {
              if (data['status'] == 200) {
                $("#event-alert").html('<div class="alert alert-success">'+ data['message'] +'</div>');
                window.location = data['url'];
              }
              else if (data['message']) {
                $("#event-alert").html('<div class="alert alert-danger">' + data['message'] + '</div>');
				$('#insert-event').find('.add_wow_loader').removeClass('btn-loading').prop('disabled', false).on('click');
              } 
              
            }
      });
  });
</script>

