image: php:7.4-cli

pipelines:
  branches:
    production:
      - step:
          name: Deploy PHP 7.4 Application via FTP
          deployment: production
          script:
            - pipe: atlassian/ftp-deploy:0.7.1
              variables:
                USER: $FTP_USER
                PASSWORD: $FTP_PASSWORD
                SERVER: $FTP_HOST
                REMOTE_PATH: $FTP_PATH
                DELETE_FLAG: 'false'
                EXTRA_ARGS: '--only-newer'
                DEBUG: 'true'
