name: Deploy to cPanel

on:
  push:
    branches:
      - release_phase2  # This means the action will run when changes are pushed to the main branch.

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Sync files to server
        run: |
          rsync -avz --delete \
          -e "ssh -o StrictHostKeyChecking=no -p ${{ secrets.SSH_PORT }}" \
          ./ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/home/zomohubc/public_html/phase2
