<?php echo Wo_LoadPage('forum/headers/header'); ?>
<div class="" id="threadreply">
	<form action="#" class="form" id="quotereply" method="post">
		<div class="page-margin mt-0">
			<div class="wow_content popular_posts_hdr flex">
				<h2>&nbsp;<?php echo $wo['lang']['reply'];?> > <?php echo $wo['reply']['post_subject']; ?></h2>

				<div class="btnss">
					<button class="btn btn-main btn-mat add_wow_loader" type="submit"><?php echo $wo['lang']['reply']; ?></button>
				</div>
			</div>
		</div>

		<div class="page-margin wow_content wow_sett_content">
			
				<div id="quotereply-alert"></div>
				<div class="wow_form_fields">
					<label for="subject"><?php echo $wo['lang']['subject']; ?></label>
					<input type="text" name="subject" id="subject" value="<?php echo($wo['reply']['post_subject']); ?>">
				</div>
				<div class="wow_form_fields mb-0">
					<label for="newquotereply"><?php echo $wo['lang']['your_reply']; ?></label>
					<textarea id="newquotereply" name="content">[quote][b]<?php echo $wo['reply']['user_data']["username"]; ?> <?php echo $wo['lang']['wrote']; ?>:[/b][nl]<?php echo $wo['reply']['post_text']; ?>[/quote]</textarea>
				</div>
			
		</div>
	</form>
	<div class="clear"></div>
</div>


<?php if (isset($wo['bbcodeditor']) && $wo['bbcodeditor']): ?>
<script>
	jQuery(document).ready(function($) {


		$('#quotereply').ajaxForm({

	      url: Wo_Ajax_Requests_File()  +  '?f=threadreply&tid=<?php echo $wo['reply']['thread_id']; ?>&fid=<?php echo $wo['reply']['forum_id']; ?>&q=1&hash=' + $('.main_session').val(),
	      beforeSend: function() {
	        Wo_progressIconLoader($('#quotereply').find('button'));
	      },
	      success: function(data) {
	        scrollToTop();
	        if (data['status'] == 200) {
	        	if (node_socket_flow == "1") {
			        socket.emit("user_notification", { to_id: data.user_id, user_id: _getCookie("user_id"), type: "added" });
			    }
	         	$("#quotereply-alert").html('<div class="alert page-margin alert-success">'+ data['message'] +'</div>');
	         	window.location = data.url;
	          
	        } else {
	        	
	         	$("#quotereply-alert").html('<div class="alert page-margin alert-danger">' + data['message'] + '</div>');
	        } 
	        Wo_progressIconLoader($('#quotereply').find('button'));
	      }
		});
		$('#newquotereply').bbcode();
		$("#newquotereply").autogrow({vertical: true, horizontal: false});

	});

</script>
	
<?php endif ?>

<?php echo Wo_LoadPage('forum/headers/footer'); ?>