<div class="page_list boosted_pages cool-style-album col-xs-6 col-sm-6 col-lg-3 real_boost_page">
	<div class="wow_content album_parent">
		<div class="avatar">
			<a href="<?php echo $wo['PageList']['url'];?>" data-ajax="?link1=timeline&u=<?php echo $wo['PageList']['page_name'];?>">
				<img src="<?php echo $wo['PageList']['cover'];?>" alt="<?php echo $wo['PageList']['page_name']; ?> Profile Picture" />
				<img class="thumb" src="<?php echo $wo['PageList']['avatar'];?>" alt="<?php echo $wo['PageList']['page_name']; ?> Profile Picture" />
			</a>
		</div>
		<div class="album-name">
			<a href="<?php echo $wo['PageList']['url'];?>" data-ajax="?link1=timeline&u=<?php echo $wo['PageList']['page_name'];?>"><h4><?php echo $wo['PageList']['page_title']; ?></h4></a>
			<a href="<?php echo $wo['PageList']['url'];?>" data-ajax="?link1=timeline&u=<?php echo $wo['PageList']['page_name'];?>"><p><?php echo $wo['PageList']['category']?></p></a>
		</div>
	</div>
</div>