<div class="modal fade" id="create-password" role="dialog">
	<div class="modal-dialog wow_mat_mdl" id="modal-dialog-update-info">
		<div class="modal-content">
			<form action="#" method="post" class="create-password">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-x"><line x1="18" y1="6" x2="6" y2="18"></line><line x1="6" y1="6" x2="18" y2="18"></line></svg></span></button>
					<h4 class="modal-title"><?php echo $wo['lang']['update_your_info']; ?></h4>
				</div>

				<div class="modal-body">
					<div class="error-container"></div>
					<div class="wow_form_fields">
						<label for="username"><?php echo $wo['lang']['choose_your_username'];?></label>
						<input id="username" name="username" type="text" placeholder="<?php echo $wo['lang']['username'];?>" onkeyup="Wo_CheckUsername(this.value);" autocomplete="off">
						<span class="help-block checking"></span> 
					</div>
					<!-- Password input-->
					<div class="wow_form_fields">
						<label for="new_password"><?php echo $wo['lang']['create_your_new_password'];?></label>
						<input id="new_password" name="new_password" type="password" placeholder="<?php echo $wo['lang']['password'];?>">
					</div>
					<!-- Password input-->
					<div class="wow_form_fields">
						<label for="repeat_new_password"><?php echo $wo['lang']['confirm_password'];?></label>
						<input id="repeat_new_password" name="repeat_new_password" type="password" placeholder="<?php echo $wo['lang']['confirm_password'];?>">
					</div>
					<input type="hidden" name="user_id" value="<?php echo $wo['user']['user_id']?>">
					<input type="hidden" name="hash_id" value="<?php echo Wo_CreateSession();?>">
				</div>
				<div class="modal-footer">
					<div class="ball-pulse"><div></div><div></div><div></div></div>
					<button id="create-password-button" type="submit" class="btn main btn-mat"><?php echo $wo['lang']['update'];?></button>
				</div>
			</form>
		</div>
	</div>
</div>