<div class="modal fade" id="logged-out-modal" role="dialog" data-backdrop="static" data-keyboard="false">
	<div class="modal-dialog modal-md wow_mat_mdl">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-x"><line x1="18" y1="6" x2="6" y2="18"></line><line x1="6" y1="6" x2="18" y2="18"></line></svg></span></button>
				<h4 class="modal-title"><?php echo $wo['lang']['session_expired']; ?></h4>
			</div>
			<div class="modal-body">
				<p><?php echo $wo['lang']['session_expired_message'];?></p>
			</div>
			<div class="modal-footer">
				<div class="ball-pulse"><div></div><div></div><div></div></div>
				<a href="<?php echo Wo_SeoLink('index.php?link1=welcome');?>" type="button" class="btn main btn-mat"><?php echo $wo['lang']['login'];?></a>
			</div>
		</div>
	</div>
</div>