				<div class="clear"></div>
		    </div>
        </div>
      </div>
   </div>
   <!-- .row -->
</div>
<script>
	jQuery(document).ready(function($) {
		$(document).on("click",".going-to-event",function(event) {
			var event_id = $(this).attr('data-event-ident');
			$.ajax({
				url: Wo_Ajax_Requests_File(),
				type: 'GET',
				dataType: 'json',
				data: {f: 'going-to-event',eid:event_id},
				success:function(data){
					if (data['status'] == 200) {
						$("[data-event="+ event_id +"]").find('.events-list-dropup-menu').html("<span class='main'>"+data['html'] +"</span>")
					}
				}
			})
			
		});

		$(document).on("click",".interested-in-event",function(event) {
			var event_id = $(this).attr('data-event-ident');
			$.ajax({
				url: Wo_Ajax_Requests_File(),
				type: 'GET',
				dataType: 'json',
				data: {f: 'interested-in-event',eid:event_id},
				success:function(data){
					if (data['status'] == 200) {
						$("[data-event="+ event_id +"]").find('.events-list-dropup-menu').html("<span class='main'>"+data['html'] +"</span>")

					}
				}
			})
		});

		$(document).on("click",".events-going-list-unset",function(event) {
			var event_id = $(this).attr('data-event-ident');
			$.ajax({
				url: Wo_Ajax_Requests_File(),
				type: 'GET',
				dataType: 'json',
				data: {f: 'notgoing-to-event',eid:event_id},
				success:function(data){
					if (data['status'] == 200) {
						$("[data-event="+event_id+"]").slideUp('fast', function() {
							$(this).remove()
						});
					}
				}
			})
		});

		let eventCount = 0; // Initialize with 0

$(".load-more-events").click(function(event) {
    let type = $(this).attr('data-events-type');
    $.ajax({
        url: Wo_Ajax_Requests_File(),
        type: 'GET',
        dataType: 'json',
        data: {
            f: 'load-more-events',
            s: type,
            offset: eventCount // Pass the count of events already loaded
        },
        success: function(data) {
            if (data.status === 200) {
                $("#events-" + type).append(data.html); // Append only new events
                eventCount += 10; // Increment by the number of events per page
                if (data.is_last_page) {
                    $(".load-more-events").hide(); // Hide button if it’s the last page
                }
            } else {
                $(".posts_load").find('.load-more').html(data.html); // Show message if no more events
            }
        }
    });
});





	});
</script>