<?php 
$message_count = Wo_CountMessages(array('new' => true,'user_id' => $wo['chatList']['user_id']));  
?>
<div class="recipient-chat-user" id="online_<?php echo $wo['chatList']['user_id'];?>">
	<div class="user-info" onclick="Wo_OpenChatTab(<?php echo $wo['chatList']['user_id'];?>);" title="<?php echo $wo['chatList']['name']; ?> (<?php echo $wo['lang']['online']; ?>)" data-toggle="tooltip" data-placement="left" data-container="body">
		<img src="<?php echo $wo['chatList']['avatar'];?>" alt="<?php echo $wo['chatList']['avatar'];?> Profile Picture" />
		<svg xmlns="http://www.w3.org/2000/svg" width="9" height="9" viewBox="0 0 24 24"><path fill="#60d465" d="M12,2A10,10 0 0,0 2,12A10,10 0 0,0 12,22A10,10 0 0,0 22,12A10,10 0 0,0 12,2Z" /></svg>

		<div class="wow_chat_list-right">
			<span class="new-message-alert <?php echo ($message_count == 0) ? 'hidden' : ''; ?>"><?php echo $message_count; ?></span>
			<span class="chat-loading-icon"></span>
		</div>
	</div>
</div>
<div class="clear"></div>