<div class="wo_about_wrapper_parent">
	<div class="wo_about_wrapper"> 
		<div class="hero hero-overlay"> 
			<div class="container">
				<h1 class="text-center"> 
					<?php echo $wo['lang']['about'];?> <?php echo $wo['config']['siteName'];?> <br> 
					<small class="site_desc text-center">Connecting the global sports industry through a secure platform dedicated to greatness in sports.</small> 
				</h1>
			</div> 
		</div> 
		<div class="full-width-picture" style="background-image: url(<?php echo $wo['config']['theme_url'];?>/img/about-us.jpg);"></div> 
	</div>
</div>

<div class="page-margin wo_about_page_margin">
   <div class="wow_content">
      <div class="setting-well">
			<div class="zomo-about-us-section">
				<img src="<?php echo $wo['config']['theme_url'];?>/img/about/about-us-social-media-icon.svg" />
				<p>A <b>sports-focused social media platform</b> designed for progressive sports content and engagement.</p>
			</div>
			<div class="zomo-about-us-section">
				<img src="<?php echo $wo['config']['theme_url'];?>/img/about/about-us-community-icon.svg" />
				<p>An <b>all-in-one interactive online community</b> for sports agents, athletes, sports fans, coaches, academies, clubs and sports-related businesses.</p>
			</div>
			<div class="zomo-about-us-section">
				<img src="<?php echo $wo['config']['theme_url'];?>/img/about/about-us-interface-icon.svg" />
				<p>A <b>user-friendly interface with cutting-edge features</b> allowing sports enthusiasts to connect, share, and collaborate.</p>
			</div>
			<div class="zomo-about-us-section">
				<img src="<?php echo $wo['config']['theme_url'];?>/img/about/about-us-connection-icon.svg" />
				<p>A platform that <b>encourages active participation</b> and <b>fosters meaningful connections</b> within the sports community.</p>
			</div>
      </div>
   </div>
</div>