<div class="page-margin">
	<div class="page-margin mt-0">
		<div class="wow_content popular_posts_hdr">
			<h2 class="flex">
				<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" class="icon_main" fill="none" stroke-linecap="round" stroke-linejoin="round"><path stroke="none" d="M0 0h24v24H0z" fill="none"></path><path d="M16 6h3a1 1 0 0 1 1 1v11a2 2 0 0 1 -4 0v-13a1 1 0 0 0 -1 -1h-10a1 1 0 0 0 -1 1v12a3 3 0 0 0 3 3h11"></path><path d="M8 8l4 0"></path><path d="M8 12l4 0"></path><path d="M8 16l4 0"></path></svg>&nbsp;
				<p>{{LANG welcome_discover}} {{LANG blog}}<b>{{LANG explore_captivating_stories}}</b></p>
			</h2>
		</div>
	</div>
	
    <div class="row">
		<div class="col-md-3 leftcol">
			<div class="blog_prnt">{{sidebar}}</div>
		</div>
        <div class="col-md-9 singlecol">
            <div class="">
                <div id="recent-blogs" class="row">

                    {{html}}

                </div>

                {{pagination}}
                <div class="clear"></div>
            </div>
        </div>
    </div>
</div>