<div class="page-margin">
	<div class="page-margin mt-0">
		<div class="wow_content popular_posts_hdr">
			<h2 class="flex">
				<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" class="icon_main" fill="none" stroke-linecap="round" stroke-linejoin="round"><path stroke="none" d="M0 0h24v24H0z" fill="none"></path><path d="M4 5m0 1a1 1 0 0 1 1 -1h4a1 1 0 0 1 1 1v4a1 1 0 0 1 -1 1h-4a1 1 0 0 1 -1 -1z"></path><path d="M14 7l6 0"></path><path d="M14 11l6 0"></path><path d="M4 15l16 0"></path><path d="M4 19l16 0"></path></svg>&nbsp;
				<p>{{LANG welcome_discover}} {{LANG posts}}<b>{{LANG explore_captivating_content}}</b></p>
			</h2>
		</div>
	</div>
	
    <div class="row">
		<div class="col-md-3 leftcol">
			<div class="post_prnt">{{sidebar}}</div>
		</div>
        <div class="col-md-9 singlecol">
            <div class="posts_load">
                {{html}}
            </div>
            <!-- #posts -->
            {{pagination}}
        </div>
    </div>
</div>