<div class="page-margin">
	<div class="page-margin mt-0">
		<div class="wow_content popular_posts_hdr">
			<h2 class="flex">
				<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" class="icon_main" fill="none" stroke-linecap="round" stroke-linejoin="round"><path stroke="none" d="M0 0h24v24H0z" fill="none"></path><path d="M4 5m0 2a2 2 0 0 1 2 -2h12a2 2 0 0 1 2 2v12a2 2 0 0 1 -2 2h-12a2 2 0 0 1 -2 -2z"></path><path d="M16 3l0 4"></path><path d="M8 3l0 4"></path><path d="M4 11l16 0"></path><path d="M8 15h2v2h-2z"></path></svg>&nbsp;
				<p>{{LANG welcome_discover}} {{LANG events}}<b>{{LANG explore_a_world_of_exciting}}</b></p>
			</h2>
		</div>
	</div>

    <div class="row">
		<div class="col-md-3 leftcol">
			<div class="event_prnt">{{sidebar}}</div>
		</div>
		<div class="col-md-9 singlecol">
			<div class="">
				{{html}}
			</div>
			<div class="clear"></div>
			{{pagination}}
			<div class="clear"></div>

		</div>
	</div>
</div>