<div class="product col-proxs-12 col-xs-6 col-sm-4 col-md-4" data-rm-blog="<?php echo $wo['fund']['id'];?>">
	<div class="view-blog fundings" id="<?php echo $wo['fund']['id']; ?>">
		<div class="avatar">
			<a href="<?php echo $wo['config']['site_url'].'/show_fund/'. $wo['fund']['hashed_id']; ?>" data-ajax="?link1=show_fund&id=<?php echo($wo['fund']['hashed_id']) ?>"><img src="<?php echo $wo['fund']['image']; ?>" alt="<?php echo $wo['fund']['title']; ?>"></a>
			<time><?php echo date("d M Y",$wo['fund']['time']); ?></time>
		</div>
		<div class="fundings_desc">
			<h3><a href="<?php echo $wo['config']['site_url'].'/show_fund/'. $wo['fund']['hashed_id']; ?>" data-ajax="?link1=show_fund&id=<?php echo($wo['fund']['hashed_id']) ?>"><?php echo stripslashes($wo['fund']['title']); ?></a></h3>
			<!--<p class="desc">
				<?php 
				$desc = str_replace('<br>', '', $wo['fund']['description']);
				echo $desc = mb_substr($desc, 0, 190, "UTF-8") . ".."; ?>
			</p>-->
		</div>
		<?php if ($wo['fund']['user_id'] == $wo['user']['id']):?>
			<div class="wow_main_fund_foot no_margin">
				<a href="<?php echo $wo['site_url'].'/edit_fund/'.$wo['fund']['hashed_id']; ?>" data-ajax="?link1=edit_fund&id=<?php echo($wo['fund']['hashed_id']) ?>" id="<?php echo $wo['fund']['id'];?>" class="btn btn-main btn-mat"><?php echo $wo['lang']['edit']; ?></a>&nbsp;&nbsp;&nbsp;
				<a class="btn btn-default btn-mat delete-fund" id="<?php echo $wo['fund']['id'];?>" data-toggle="tooltip" title="<?php echo $wo['lang']['delete']; ?>">
					<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" stroke-width="1.75" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round"><path stroke="none" d="M0 0h24v24H0z" fill="none"></path><path d="M4 7l16 0"></path><path d="M10 11l0 6"></path><path d="M14 11l0 6"></path><path d="M5 7l1 12a2 2 0 0 0 2 2h8a2 2 0 0 0 2 -2l1 -12"></path><path d="M9 7v-3a1 1 0 0 1 1 -1h4a1 1 0 0 1 1 1v3"></path></svg>
				</a>
			</div>
		<?php endif;?>
	</div>
</div>