<div class="col-xs-12 col-md-6" id="game_<?php echo $wo['game']['id'];?>">
	<div class="wow_content wo_game_style">
		<a href="<?php echo $wo['game']['url'];?>" data-ajax="?link1=game&id=<?php echo $wo['game']['id'];?>">
			<div class="avatar">
				<img src="<?php echo $wo['game']['game_avatar'];?>" alt="<?php echo $wo['game']['game_name']; ?> Profile Picture" />
			</div>
			<div class="game-name"><?php echo $wo['game']['game_name']; ?></div>
			<p><?php echo $wo['lang']['last_play'];?> <?php echo Wo_Time_Elapsed_String($wo['game']['last_play']);?></p>
			<div class="btn btn-main btn-mat btn-block"><?php echo $wo['lang']['play'];?></div>
		</a>
	</div>
</div>