<div class="page-margin">
	<div class="row">
		<div class="col-md-2 leftcol"><?php echo Wo_LoadPage("sidebar/left-sidebar"); ?></div>
		<div class="col-md-7 middlecol">
			<div class="page-margin mt-0">
				<div class="wow_content popular_posts_hdr">
					<h2><svg width="18" height="18" viewBox="0 0 18 18" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M11.25 9C11.25 10.2426 10.2426 11.25 9 11.25C7.75736 11.25 6.75 10.2426 6.75 9C6.75 7.75736 7.75736 6.75 9 6.75C10.2426 6.75 11.25 7.75736 11.25 9Z" class="icon_main" stroke-width="1.5"></path><path d="M16.5 9L14 9" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"></path><path d="M1.5 9L4 9" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"></path><path d="M9 16.5L9 14M9 1.5L9 4" class="icon_main" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"></path><path d="M9 1.5L9 4" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"></path><path d="M9 16.5L9 14" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"></path></svg>&nbsp;<?php echo $wo['lang']['games']; ?></h2>
				</div>
			</div>
			
			<div class="page-margin wow_content wow_big_head_link">
				<ul class="list-unstyled">
					<li><a href="<?php echo Wo_SeoLink('index.php?link1=new-game'); ?>" data-ajax="?link1=new-game"><?php echo $wo['lang']['latest_games'] ?></a></li>
					<li class="active"><a data-ajax="?link1=games" href="<?php echo Wo_SeoLink('index.php?link1=games');?>"><?php echo $wo['lang']['my_games']; ?></a></li>
				</ul>
			</div>
			
			<div class="row wow_games">
				<?php
					$pages = Wo_GetMyGames();
					if (count($pages) > 0) {
						foreach ($pages as $wo['game']) {
							echo Wo_LoadPage('games/game-list');
						}
					} else {
						echo '<div class="col-md-12"><div class="wow_content"><div class="empty_state"><svg width="18" height="18" viewBox="0 0 18 18" fill="none" xmlns="http://www.w3.org/2000/svg">
<path d="M11.25 9C11.25 10.2426 10.2426 11.25 9 11.25C7.75736 11.25 6.75 10.2426 6.75 9C6.75 7.75736 7.75736 6.75 9 6.75C10.2426 6.75 11.25 7.75736 11.25 9Z" class="icon_main" stroke-width="1.5"></path>
<path d="M16.5 9L14 9" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"></path>
<path d="M1.5 9L4 9" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"></path>
<path d="M9 16.5L9 14M9 1.5L9 4" class="icon_main" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"></path>
<path d="M9 1.5L9 4" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"></path>
<path d="M9 16.5L9 14" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"></path>
</svg>' . $wo['lang']['no_games_found'] . '</div></div></div>';
					}
				?>
				<div class="clear"></div>
			</div>
		</div>
		<!-- .col-md-8 -->
		<?php echo Wo_LoadPage('sidebar/content');?>
	</div>
	<!-- .row -->
</div>