<div class="cool-style-album profi_groups user_list col-xs-6 col-sm-6 col-lg-4" data-user-id="<?php echo $wo['UsersList']['user_id'];?>">
	<div class="wow_content album_parent">
		<div class="avatar">
			<a href="<?php echo $wo['UsersList']['url'];?>" data-ajax="?link1=timeline&u=<?php echo $wo['UsersList']['username']?>">
				<img src="<?php echo $wo['UsersList']['avatar'];?>" alt="<?php echo $wo['UsersList']['name']; ?> Profile Picture" />
			</a>
		</div>
		<div class="album-name">
			<a href="<?php echo $wo['UsersList']['url'];?>" data-ajax="?link1=timeline&u=<?php echo $wo['UsersList']['username']?>"><h4><?php echo $wo['UsersList']['name']; ?></h4></a>
			
			<?php if (!empty($wo['UsersList']['family_member'])){ ?>
				<p data-family-member="<?php echo $wo['UsersList']['user_id'];?>"><?php echo $wo['UsersList']['family_member']; ?></p>
			<?php } else { ?>
				<?php if($wo['config']['user_lastseen'] == 1 && $wo['UsersList']['showlastseen'] != 0): ?>
					<p>
						<?php echo Wo_UserStatus($wo['UsersList']['user_id'],$wo['UsersList']['lastseen']); ?>
					</p>
				<?php endif; ?>
			<?php } ?>
		</div>
		<div class="user-follow-button">
			<?php echo Wo_GetFollowButton($wo['UsersList']['user_id']);?>
			<?php if (!empty($wo['UsersList']['family_member'])): ?>
				<span data-family-member="<?php echo $wo['UsersList']['user_id'];?>">
					<button type="button" class="btn btn-default btn-sm" onclick="$('#delete_family_mbr_modal').attr('data-family-member-id', '<?php echo $wo['UsersList']['id'];?>').modal('show');">
						<i class="fa fa-times progress-icon" data-icon="fa-times"></i>
						<span class="button-text"> <?php echo $wo['lang']['delete'];?></span>
					</button>
				</span>
			<?php endif; ?>
		</div>
	</div>
</div>