<div class="page-margin mt-0">
	<div class="wow_content popular_posts_hdr flex">
		<h2>&nbsp;<?php echo $wo['lang']['developers'] ?></h2>
		<div class="btnss">
			<a class="btn btn-main btn-mat" data-ajax="?link1=create-app" href="<?php echo Wo_SeoLink('index.php?link1=create-app');?>"><?php echo $wo['lang']['create'] ?> App</a>
		</div>
	</div>
</div>

<div class="page-margin wow_content wow_big_head_link mb-0">
	<ul class="list-unstyled">
		<li class="<?php echo ($wo['active'] == 1) ? 'active': ''; ?>"><a href="<?php echo Wo_SeoLink('index.php?link1=developers') ?>" data-ajax="?link1=developers"><?php echo $wo['lang']['developers'] ?></a></li>
		<li class="<?php echo ($wo['active'] == 2) ? 'active': ''; ?>"><a href="<?php echo Wo_SeoLink('index.php?link1=developers?page=share') ?>" data-ajax="?link1=developers&page=share">Share Plugin</a></li>
	</ul>
</div>