<li class="<?php echo($wo['user_status']['have_not_seen'] ? "not_seen_story" : ""); ?>">
	<a class="avatar see_all_stories" data_story_user_id="<?php echo $wo['user_status']['user_data']['user_id']?>" data_story_type="friends">
		<img src="<?php echo $wo['user_status']['thumb']['filename'];?>" >
	</a>
	<p><a class="see_all_stories" data_story_user_id="<?php echo $wo['user_status']['user_data']['user_id']?>" data_story_type="friends"><?php echo $wo['user_status']['user_data']['name']?></a></p>
</li>