<nav class="ads-navbar-wrapper" role="navigation">
	<div class="ads_mini_wallet">
		<p><?php echo $wo['lang']['my_balance'];?></p>
		<h3><?php echo Wo_GetCurrency($wo['config']['ads_currency']); ?><?php echo number_format($wo['user']['wallet'],2);?></h3>
	</div>
	<ul class="ads-nav list-unstyled">
		<?php if ($wo['config']['monetization'] == 1) { ?>
			<li>
				<a href="<?php echo Wo_SeoLink('index.php?link1=subscriptions-monetizations'); ?>" data-ajax="?link1=subscriptions&type=monetizations" class="active" data-ajax="?link1=subscriptions&type=monetizations"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M12,8H4A2,2 0 0,0 2,10V14A2,2 0 0,0 4,16H5V20A1,1 0 0,0 6,21H8A1,1 0 0,0 9,20V16H12L17,20V4L12,8M21.5,12C21.5,13.71 20.54,15.26 19,16V8C20.53,8.75 21.5,10.3 21.5,12Z" /></svg> <?php echo $wo['lang']['monetization']; ?></a>
			</li>
		<?php } ?>
	</ul>
	<div class="clear"></div>
</nav>
