<tr class="forum-mbr-list" id="<?php echo $wo['member']['id']; ?>">

    <td>
        <p>
            <b>
                <a href="/<?php echo $wo['member']['username'] ?>/" data-ajax="?link1=timeline&u=<?php echo $wo['member']['username'] ?>"><img src="<?php echo $wo['member']['avatar'] ?>" width="24" height="24"/>&nbsp;&nbsp;<?php echo $wo['member']['name'] ?></a>
				<?php if ($wo['member']['admin'] == 1): ?>
					<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="18" height="18"><title><?php echo $wo['lang']['site_admin']; ?></title><path fill="currentColor" d="M12 1L21 5V11C21 16.55 17.16 21.74 12 23C6.84 21.74 3 16.55 3 11V5L12 1M16 14H8V15.5C8 15.77 8.19 15.96 8.47 16L8.57 16H15.43C15.74 16 15.95 15.84 16 15.59L16 15.5V14M17 8L17 8L14.33 10.67L12 8.34L9.67 10.67L7 8L7 8L8 13H16L17 8Z" /></svg>
				<?php else: ?>
				<?php endif; ?>
            </b>
        </p>
    </td>
    <td>
        <span><?php echo Wo_Time_Elapsed_String($wo['member']['joined']) ?></span>
    </td>
    <td>
        <span><?php echo Wo_Time_Elapsed_String($wo['member']['lastseen']) ?></span>
        
    </td>


    <td><?php echo($wo['member']['forum_posts']) ?></td>
    <td>
          <span><?php echo($wo['member']['referrer']) ?></span>
    </td>
</tr>