<div class="wow_content mythread-list section-list" data-thread-ident="<?php echo $wo['thread']['id']; ?>">
	<div class="topic_icon">
		<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M20,2H4A2,2 0 0,0 2,4V22L6,18H20A2,2 0 0,0 22,16V4A2,2 0 0,0 20,2M6,9H18V11H6M14,14H6V12H14M18,8H6V6H18"></path></svg>
	</div>
	<div class="forum-meta-d titles">
		<div>
			<a href="<?php echo $wo['thread']['url'];?>" data-ajax="?link1=showthread&tid=<?php echo $wo['thread']['id'];?>" class="ftitle">
				<?php 
					if(strlen($wo['thread']['headline']) > 55){
						echo Wo_GetShortTitle($wo['thread']['headline'], false, 50);
					}
					else {
						echo $wo['thread']['headline'];
					}
				?>
			</a>
		</div>
		<div class="small fdesc">
			<i><?php echo $wo['lang']['by']; ?></i> <a href="<?php echo $wo['thread']['author_url']; ?>" data-ajax="?link1=timeline&u=<?php echo $wo['thread']['user_data']['username']; ?>"><?php echo $wo['thread']['user_data']['username']; ?></a> <?php echo Wo_Time_Elapsed_String($wo['thread']['posted']); ?>
		</div>
	</div>
	<div class="forum-meta-d small">
		<div>
			<a class="btn btn-default btn-mat" href="<?php echo $wo['thread']['edit_url']; ?>" data-ajax="?link1=edithread&tid=<?php echo $wo['thread']['id'];?>">
				<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M20.71,7.04C21.1,6.65 21.1,6 20.71,5.63L18.37,3.29C18,2.9 17.35,2.9 16.96,3.29L15.12,5.12L18.87,8.87M3,17.25V21H6.75L17.81,9.93L14.06,6.18L3,17.25Z" /></svg>
			</a>
			<a class="btn btn-default btn-mat delete-thread" id="<?php echo $wo['thread']['id']; ?>">
				<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M19,4H15.5L14.5,3H9.5L8.5,4H5V6H19M6,19A2,2 0 0,0 8,21H16A2,2 0 0,0 18,19V7H6V19Z" /></svg>
			</a>
		</div>
	</div>
	<div class="forum-meta-d topics">
		<div>
			<span><b><?php echo $wo['lang']['last_post']; ?></b> <?php if ($wo['thread']['last_post'] > 0): ?>
			<?php echo Wo_Time_Elapsed_String($wo['thread']['last_post']); ?>
		<?php else: ?>
			<?php echo $wo['lang']['never'] ?>
		<?php endif; ?></span>
			<span><b><?php echo $wo['lang']['views']; ?></b> <?php echo $wo['thread']['views']; ?></span>
		</div>
	</div>
</div>