<div class="container-fluid">
    <div>
        <h3>Advertisements System Settings</h3>
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item">
                    <a href="#">Home</a>
                </li>
                <li class="breadcrumb-item">
                    <a href="#">Advertisements</a>
                </li>
                <li class="breadcrumb-item active" aria-current="page">Advertisements System Settings</li>
            </ol>
        </nav>
    </div>
    <!-- Vertical Layout -->
    <div class="row">
        <div class="col-lg-6 col-md-6">
            <div class="card">
                <div class="card-body">
                    <h6 class="card-title">Advertisements Settings</h6>
                    <div class="ads-settings-alert"></div>
                    <form class="ads-settings" method="POST">
                      
                          <div class="float-left">
                              <label for="user_ads" class="main-label">Advertisements System</label>
                              <br><small class="admin-info">Allow users to create ads.</small>
                          </div>
                          <div class="form-group float-right switcher">
                              <input type="hidden" name="user_ads" value="0" />
                              <input type="checkbox" name="user_ads" id="chck-user_ads" value="1" <?php echo ($wo['config']['user_ads'] == 1) ? 'checked': '';?>>
                              <label for="chck-user_ads" class="check-trail"><span class="check-handler"></span></label>
                          </div>
                          <div class="clearfix"></div>
                          <hr>
                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">Cost By View</label>
                                <input type="text" id="ad_v_price" name="ad_v_price" class="form-control" value="<?php echo $wo['config']['ad_v_price'];?>">
                                <small class="admin-info">Set a price for ads impressions.</small>
                            </div>
                        </div>
                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">Cost By Click</label>
                                <input type="text" id="ad_c_price" name="ad_c_price" class="form-control" value="<?php echo $wo['config']['ad_c_price'];?>">
                                <small class="admin-info">Set a price for ads clicks.</small>
                            </div>
                        </div>
                        <!-- <div class="form-group form-float">
                            <div class="form-line">
                                <input type="text" id="video_ad_skip" name="video_ad_skip" class="form-control" value="<?php echo $wo['config']['video_ad_skip'];?>">
                                <label class="form-label">Video ads skip button seconds</label>
                            </div>
                        </div> -->
                        <div class="clearfix"></div>
                        <input type="hidden" name="hash_id" value="<?php echo Wo_CreateSession();?>">
                    </form>
                </div>
            </div>
        </div>
        <div class="col-lg-6 col-md-6">
            <div class="card">
                <div class="card-body">
                    <h6 class="card-title">Top Up <?php echo $wo['user']['name'] ?>'s Wallet</h6>
                    <div class="top-up-settings-alert"></div>
                    <form class="top-up-settings" method="POST">
                        <div class="form-group form-float">
                            <div class="form-line">
                                <label class="form-label">Amount</label>
                                <input type="text" id="amount" name="amount" class="form-control" value="<?php echo $wo['user']['wallet'];?>">
                                <small class="admin-info">You can top your own wallet from here, set any number.</small>
                            </div>
                        </div>
                        <input type="hidden" name="hash_id" value="<?php echo Wo_CreateSession();?>">
                        <button type="submit" class="btn btn-primary m-t-15 waves-effect">Top Up</button>
                    </form>
                </div>
            </div>
        </div>
        <!-- <div class="col-lg-12 col-md-12">
            <div class="card">
                <div class="card-body">
                    <h6 class="card-title">Countries</h6>
                   <input type="hidden" id="hash_id" name="hash_id" value="<?php echo Wo_CreateSession();?>">
                   <div class="clearfix"></div>
                   <div class="table-responsive1">
                        <table class="table table-bordered table-striped table-hover">
                            <thead>
                                <tr>
                                      <th>ID</th>
                                      <th>Country Name</th>
                                      <th>View Cost</th>
                                      <th>Click Cost</th>
                                      <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                               <?php 
                               foreach ($wo['countries_ads']  as $wo['country_id'] => $wo['value']) {
                                  echo Wo_LoadAdminPage('ads-settings/list');
                                }
                               ?>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div> -->
        <div class="clearfix"></div>
    </div>
    <!-- #END# Vertical Layout -->

<div class="modal fade" id="country_adsModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content modal_content_back">
      <div class="modal-header">
        <h5 class="modal-title">Edit Country Cost</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="country_ads_form_alert"></div>
        <form class="country_ads_form" method="POST" id="modal-body-langs">
          <div class="row">
                <div class="col-md-12">
                    <div class="form-group form-float">
                        <div class="form-line focused">
                            <label class="form-label">View Cost</label>
                            <input type="number" name="view_cost" class="form-control" value="" id="view_cost">
                        </div>
                    </div>
                </div>
                <div class="col-md-12">
                    <div class="form-group form-float">
                        <div class="form-line focused">
                            <label class="form-label">Click Cost</label>
                            <input type="number" name="click_cost" class="form-control" value="" id="click_cost">
                        </div>
                    </div>
                </div>
          </div>

          <input type="hidden" name="hash_id" value="<?php echo Wo_CreateSession();?>">
          <div class="modal-footer">
        
        <button type="button" class="btn btn-primary modal_close_btn" data-dismiss="modal">CLOSE</button>
        <button type="submit" class="btn btn-success" id="edit_custom_field_button">SAVE CHANGES</button>
      </div>
        </form>
        
      </div>
      
    </div>
  </div>
</div>
<script>
    function getCountryAds(id) {
        $.post( Wo_Ajax_Requests_File() + '?f=admin_setting&s=get_country_ad', {
            hash_id: $('input[name=hash_id]').val(),
            id: id
        }, function (data) {
            if (data.status == 200) {
                $('#click_cost').val(data.data.click_cost);
                $('#view_cost').val(data.data.view_cost);
                $('#country_adsModal').modal('show');
            } else {
            }
        });
    }

$(function() {
    $('.switcher input[type=checkbox]').click(function () {
        setToTrue = 0;
        if ($(this).is(":checked") === true) {
            setToTrue = 1;
        }
        var configName = $(this).attr('name');
        var hash_id = $('input[name=hash_id]').val();
        var objData = {};
        objData[configName] = setToTrue;
        objData['hash_id'] = hash_id;
        $.post( Wo_Ajax_Requests_File() + '?f=admin_setting&s=update_general_setting', objData);
    });

    var setTimeOutColor = setTimeout(function (){});
    $('select').on('change', function() {
         clearTimeout(setTimeOutColor);
        var thisElement = $(this);
        var configName = thisElement.attr('name');
        var hash_id = $('input[name=hash_id]').val();
        var objData = {};
        objData[configName] = this.value;
        objData['hash_id'] = hash_id;
        thisElement.addClass('warning');
        $.post( Wo_Ajax_Requests_File() + '?f=admin_setting&s=update_general_setting', objData, function (data) {
            if (data.status == 200) {
                thisElement.removeClass('warning');
                thisElement.addClass('success');
            } else {
                thisElement.addClass('error');
            }
            var setTimeOutColor = setTimeout(function () {
                thisElement.removeClass('success');
                thisElement.removeClass('warning');
                thisElement.removeClass('error');
            }, 2000);
        });
    });
    $('input[type=text], input[type=number]').on('input', delay(function() {
            clearTimeout(setTimeOutColor);
            var thisElement = $(this);
            var configName = thisElement.attr('name');
            var hash_id = $('input[name=hash_id]').val();
            var objData = {};
            objData[configName] = this.value;
            objData['hash_id'] = hash_id;
            thisElement.addClass('warning');
            $.post( Wo_Ajax_Requests_File() + '?f=admin_setting&s=update_general_setting', objData, function (data) {
                if (data.status == 200) {
                    thisElement.removeClass('warning');
                    thisElement.addClass('success');
                } else {
                    thisElement.addClass('error');
                }
                var setTimeOutColor = setTimeout(function () {
                    thisElement.removeClass('success');
                    thisElement.removeClass('warning');
                    thisElement.removeClass('error');
                }, 2000);
                //thisElement.focus();
            });
    }, 500));

    var form_top_settings = $('form.top-up-settings');
    form_top_settings.ajaxForm({
        url: Wo_Ajax_Requests_File() + '?f=admin_setting&s=top_up_wallet',
        beforeSend: function() {
            form_top_settings.find('.waves-effect').text('Please wait..');
        },
        success: function(data) {
            if (data.status == 200) {
                $("html, body").animate({ scrollTop: 0 }, "slow");
                $('.top-up-settings-alert').html('<div class="alert alert-success"><i class="fa fa-check"></i> Amount added to your wallet successfully.</div>');
                setTimeout(function () {
                    $('.top-up-settings-alert').empty();
                }, 2000);
            }
            form_top_settings.find('.waves-effect').text('Top Up');
        }
    });
});
</script>