<div class="page-margin">
	<div class="row">
		<div class="col-md-2 leftcol"><?php echo Wo_LoadPage("sidebar/left-sidebar"); ?></div>
		<div class="col-md-7 singlecol">
			<form class="contact-us-form form-horizontal" method="post">
				<div class="page-margin mt-0">
					<div class="wow_content popular_posts_hdr flex">
						<h2>&nbsp;<?php echo $wo['lang']['contact_us'];?></h2>
						<div class="btnss">
							<button class="btn btn-main btn-mat add_wow_loader" type="submit" name="send" id="send" disabled><?php echo $wo['lang']['send']; ?></button>
						</div>
					</div>
				</div>
				
				<div class="page-margin wow_content wow_sett_content">
				<div class="contact-us-alert setting-update-alert"></div>
				
					<div class="wow_form_fields">
						<label for="first_name"><?php echo $wo['lang']['first_name']; ?></label>
						<input id="first_name" name="first_name" type="text">
					</div>
					<div class="wow_form_fields">
						<label for="last_name"><?php echo $wo['lang']['last_name']; ?></label>
						<input id="last_name" name="last_name" type="text">
					</div>
					<div class="wow_form_fields">
						<label for="email"><?php echo $wo['lang']['email']; ?></label>
						<input id="email" name="email" type="email">
					</div>
					<div class="wow_form_fields">
						<label for="message"><?php echo $wo['lang']['message']; ?></label>
						<textarea name="message" id="message" rows="5"></textarea>
					</div>
					<?php if ($wo['config']['reCaptcha'] == 1 && !empty($wo['config']['reCaptchaKey'])) { ?>
						<div class="wow_form_fields">
							<div id="g-recaptcha-widget"></div>
						</div>
					<?php } ?>
					<div class="terms">
						<div class="round-check">
							<input type="checkbox" name="accept_terms" id="accept_terms" onchange="activateButton(this)">
							<label for="accept_terms"><?php echo str_replace('{privacy}', '<a href="'.Wo_SeoLink('index.php?link1=terms&type=privacy-policy').'">'.$wo['lang']['privacy_policy'].'</a>', $wo['lang']['terms_contact'])  ?></label>
						</div>
						<div class="clear"></div>
					</div>

				</div>
			</form>
		</div>
	</div>
	<!-- .row -->
</div>
<!-- .page-margin -->
<script>
	<?php if ($wo['config']['reCaptcha'] == 1 && !empty($wo['config']['reCaptchaKey'])) { ?>
	setTimeout(() => {
		widgetId2 = grecaptcha.render(document.getElementById('g-recaptcha-widget'), {
	    'sitekey' : "<?php echo $wo['config']['reCaptchaKey']?>"
	  });
	},500);
	<?php } ?>
function activateButton(element) {
	if(element.checked) {
		document.getElementById("send").disabled = false;
	}
	else  {
		document.getElementById("send").disabled = true;
	}
};

   $(function() {
     $('form.contact-us-form').ajaxForm({
       url: Wo_Ajax_Requests_File() + '?f=contact_us',
       beforeSend: function() {
		 $('form.contact-us-form').find('.add_wow_loader').addClass('btn-loading');
       },
       success: function(data) {
         if (data.status == 200) {
            $('.contact-us-alert').html('<div class="alert alert-success">' + data.message + '</div>');
            $('.alert-success').fadeIn(300);
         } else {
             var errors = data.errors.join("<br>");
             $('.contact-us-alert').html('<div class="alert alert-danger">' + errors + '</div>');
             $('.alert-danger').fadeIn(300);
         }
         $('form.contact-us-form').find('.add_wow_loader').removeClass('btn-loading');
       }
     });
   });
</script>