<div class="modal fade" id="calling-modal" role="dialog" data-backdrop="static" data-keyboard="false">
	<div class="modal-dialog wow_mat_mdl modal-sm">
		<div class="modal-content text-center wo_calling_modals video">
			<img src="<?php echo $wo['calling_user']['avatar'];?>">
			<div class="modal-header">
				<div class="avatar">
					<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M17,10.5V7A1,1 0 0,0 16,6H4A1,1 0 0,0 3,7V17A1,1 0 0,0 4,18H16A1,1 0 0,0 17,17V13.5L21,17.5V6.5L17,10.5Z" /></svg>
					<img width="100" height="100" src="<?php echo $wo['calling_user']['avatar'];?>">
				</div>
				<h4 class="modal-title"><?php echo $wo['lang']['calling'];?> <?php echo $wo['calling_user']['username'];?> ..</h4>
			</div>
			<div class="modal-body">
				<p><?php echo $wo['lang']['calling_desc'];?></p>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-default btn-mat cancel-call" onclick="Wo_CancelCall();"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24"><path fill="currentColor" d="M12.0007 10.5865L16.9504 5.63672L18.3646 7.05093L13.4149 12.0007L18.3646 16.9504L16.9504 18.3646L12.0007 13.4149L7.05093 18.3646L5.63672 16.9504L10.5865 12.0007L5.63672 7.05093L7.05093 5.63672L12.0007 10.5865Z"></path></svg> <?php echo $wo['lang']['cancel'];?></button>
			</div>
		</div>
	</div>
</div>