<div class="modal fade sun_modal" id="edit-job-modal-<?php echo $wo['story']['job']['id']; ?>" role="dialog">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="wow_pops_head">
				<svg height="100px" preserveAspectRatio="none" version="1.1" viewBox="0 0 300 100" width="300px" xmlns="http://www.w3.org/2000/svg"><path d="M30.913,43.944c0,0,42.911-34.464,87.51-14.191c77.31,35.14,113.304-1.952,146.638-4.729 c48.654-4.056,69.94,16.218,69.94,16.218v54.396H30.913V43.944z" fill="currentColor" opacity="0.6"></path> <path d="M-35.667,44.628c0,0,42.91-34.463,87.51-14.191c77.31,35.141,113.304-1.952,146.639-4.729 c48.653-4.055,69.939,16.218,69.939,16.218v54.396H-35.667V44.628z" fill="currentColor" opacity="0.6"></path> <path d="M-34.667,62.998c0,0,56-45.667,120.316-27.839C167.484,57.842,197,41.332,232.286,30.428 c53.07-16.399,104.047,36.903,104.047,36.903l1.333,36.667l-372-2.954L-34.667,62.998z" fill="currentColor"></path></svg>
				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M19,6.41L17.59,5L12,10.59L6.41,5L5,6.41L10.59,12L5,17.59L6.41,19L12,13.41L17.59,19L19,17.59L13.41,12L19,6.41Z"></path></svg></button>
				<h4><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M10,2H14A2,2 0 0,1 16,4V6H20A2,2 0 0,1 22,8V19A2,2 0 0,1 20,21H4C2.89,21 2,20.1 2,19V8C2,6.89 2.89,6 4,6H8V4C8,2.89 8.89,2 10,2M14,6V4H10V6H14Z"></path></svg> <?php echo $wo['lang']['edit_job'] ?></h4>
			</div>
			
			<form class="edit-job-form form-horizontal" method="post">
				<div class="modal-body">
					<div class="wo_create_job_box">
						<div class="app-general-alert setting-update-alert"></div>
						<div class="clear"></div>
						<div class="">
							<!-- Text input-->
							<div class="row">
								<div class="col-lg-6">
									<div class="wow_form_fields">
										<label for="job_title"><?php echo $wo['lang']['job_title'] ?></label>  
										<input id="job_title" name="job_title" type="text" placeholder="<?php echo $wo['lang']['job_title'] ?>" value="<?php echo $wo['story']['job']['title']; ?>">
									</div>
								</div>
								<div class="col-lg-6">
									<div class="wow_form_fields">
										<label for="location"><?php echo $wo['lang']['location'] ?></label>  
										<input id="location" name="location" type="text" placeholder="<?php echo $wo['lang']['location'] ?>" value="<?php echo $wo['story']['job']['location']; ?>">
									</div>
								</div>
							</div>
							
							<div class="wow_form_fields">
								<label><?php echo $wo['lang']['salary_range'] ?></label>
								<div class="wo_create_job_box_flex">
									<div class="sun_input">
										<input id="minimum" class="edit_job" name="minimum" type="text" placeholder="<?php echo $wo['config']['currency_symbol_array'][$wo['config']['currency']] .' '. $wo['lang']['minimum'] ?>" oninput="this.value = this.value.replace(/[^0-9.]/g, '').replace(/(\..*)\./g, '$1');" value="<?php echo $wo['story']['job']['minimum']; ?>">
									</div>
									<div class="sun_input">
										<input id="maximum" class="edit_job" name="maximum" type="text" placeholder="<?php echo $wo['config']['currency_symbol_array'][$wo['config']['currency']] .' '. $wo['lang']['maximum'] ?>" oninput="this.value = this.value.replace(/[^0-9.]/g, '').replace(/(\..*)\./g, '$1');" value="<?php echo $wo['story']['job']['maximum']; ?>">
									</div>
									<div class="sun_input">
										<select id="salary_date" name="salary_date">
											<option value="per_hour" <?php echo $wo['story']['job']['salary_date'] == 'per_hour' ? 'selected' : ''; ?>><?php echo $wo['lang']['per_hour'] ?></option>
											<option value="per_day" <?php echo $wo['story']['job']['salary_date'] == 'per_day' ? 'selected' : ''; ?>><?php echo $wo['lang']['per_day'] ?></option>
											<option value="per_week" <?php echo $wo['story']['job']['salary_date'] == 'per_week' ? 'selected' : ''; ?>><?php echo $wo['lang']['per_week'] ?></option>
											<option value="per_month" <?php echo $wo['story']['job']['salary_date'] == 'per_month' ? 'selected' : ''; ?>><?php echo $wo['lang']['per_month'] ?></option>
											<option value="per_year" <?php echo $wo['story']['job']['salary_date'] == 'per_year' ? 'selected' : ''; ?>><?php echo $wo['lang']['per_year'] ?></option>
										</select>
									</div>
								</div>
							</div>

							<div class="row">
								<div class="col-lg-6">
									<div class="wow_form_fields">
										<label for="job_type"><?php echo $wo['lang']['job_type'] ?></label> 
										<select id="job_type" name="job_type">
											<option value="full_time" <?php echo $wo['story']['job']['job_type'] == 'full_time' ? 'selected' : ''; ?>><?php echo $wo['lang']['full_time'] ?></option>
											<option value="part_time" <?php echo $wo['story']['job']['job_type'] == 'part_time' ? 'selected' : ''; ?>><?php echo $wo['lang']['part_time'] ?></option>
											<option value="internship" <?php echo $wo['story']['job']['job_type'] == 'internship' ? 'selected' : ''; ?>><?php echo $wo['lang']['internship'] ?></option>
											<option value="volunteer" <?php echo $wo['story']['job']['job_type'] == 'volunteer' ? 'selected' : ''; ?>><?php echo $wo['lang']['volunteer'] ?></option>
											<option value="contract" <?php echo $wo['story']['job']['job_type'] == 'contract' ? 'selected' : ''; ?>><?php echo $wo['lang']['contract'] ?></option>
										</select>
									</div>
								</div>
								<div class="col-lg-6">
									<div class="wow_form_fields">
										<label for="category"><?php echo $wo['lang']['category'] ?></label>  
										<select name="category" id="category">
											<?php foreach ($wo['job_categories'] as $category_id => $category_name) {?>
												<option value="<?php echo $category_id?>" <?php echo $wo['story']['job']['category'] == $category_id ? 'selected' : ''; ?>><?php echo $category_name; ?></option>
											<?php } ?>
										</select>
									</div>
								</div>
							</div>
							<div class="wow_form_fields">
								<label for="description"><?php echo $wo['lang']['description'] ?></label>  
								<textarea name="description" rows="3" id="description" placeholder="<?php echo $wo['lang']['description'] ?>"><?php echo br2nl($wo['story']['job']['description']); ?></textarea>
								<span class="help-block"><?php echo $wo['lang']['job_des_text'] ?></span>	
							</div>
						</div>

						<div class="publisher-hidden-option">
							<div id="progress" class="create-product-progress">
								<span id="percent" class="create-product-percent <?php echo Wo_RightToLeft('pull-right');?>">0%</span>
								<div class="progress">
									<div id="bar" class="progress-bar active create-product-bar"></div> 
								</div>
								<div class="clear"></div>
							</div>
						</div>

						<input type="hidden" name="job_id" id="job_id" class="form-control input-md" value="<?php echo $wo['story']['job']['id'];?>">
						<input type="hidden" name="hash_id" value="<?php echo Wo_CreateSession();?>">
					</div>
				</div>
				<div class="form-group last-sett-btn modal-footer">
					<div class="ball-pulse"><div></div><div></div><div></div></div>
					<button type="submit" class="btn btn-main btn-mat"><?php echo $wo['lang']['publish'] ?></button>
				</div>
			</form>
		</div>
	</div>
</div>