<div class="reels_list {{CLASS}}" data-id="{{ID}}" data-reel-url="{{URL}}">
   <div class="lightbox-content post wo_imagecombo_lbox lightpost-{{STORY id}} wo_reels_cont" id="post-{{STORY id}}" data-post-id="{{STORY id}}" data-type="reels">
      <div class="story-img reels-img">
         <span class="changer reels-previous-btn" onclick="Wo_PreviousReelVideo();">
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-chevron-left" color="#fff">
               <polyline points="15 18 9 12 15 6"></polyline>
            </svg>
         </span>
         <span class="changer reels-next-btn" onclick="Wo_NextReelVideo();">
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-chevron-right" color="#fff">
               <polyline points="9 18 15 12 9 6"></polyline>
            </svg>
         </span>
         <div class="sun_img_innr">
            <?php if ($wo['loggedin'] && ($wo['story']['user_id'] == $wo['user']['user_id'] || Wo_IsAdmin())) { ?>
			<button type="button" class="btn btn-delete-reel" onclick="Wo_OpenReelDeleteBox({{ID}},'show');"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M19,4H15.5L14.5,3H9.5L8.5,4H5V6H19M6,19A2,2 0 0,0 8,21H16A2,2 0 0,0 18,19V7H6V19Z"></path></svg></button>
            <?php } ?>
			
            <div id="draggableHelper" style="display: table-cell;vertical-align: middle;">
               {{VIDEO}}
            </div>
         </div>
      </div>
      <div class="comment-section reels-section">
        <div class="wow_lightbox_right">
            <div class="comment-section-inner">
                <div class="comment-inner-header">
                    <div class="<?php echo Wo_RightToLeft('pull-right'); ?> close-lightbox"
                         onclick="Wo_DisableCommentBox()">
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none"
                             stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
                             class="feather feather-x" style="margin-top: 0px;width: 24px;height: 24px;">
                            <line x1="18" y1="6" x2="6" y2="18"></line>
                            <line x1="6" y1="6" x2="18" y2="18"></line>
                        </svg>
                    </div>
                    <div class="user-avatar <?php echo Wo_RightToLeft('pull-left'); ?>">
                        <img src="{{PUBLISHER avatar}}" alt="">
                    </div>
                    <div class="user-name h5">
                        {{PUBLISHER name}}
                    </div>
                    <h6>
                        <div class="time" style="color:#9197a3">
                            <span class="ajax-time"
                                  title="<?php echo date('c', $wo['story']['time']); ?>"><?php echo Wo_Time_Elapsed_String($wo['story']['time']); ?></span>
                        </div>
                    </h6>
                </div>
                <div class="clear"></div>
                <div class="comment-inner-middle"
                     <?php if ($wo['loggedin'] != true) { ?>onclick="location.href= '<?php echo $wo['config']['site_url']; ?>'"<?php } ?>>
                    <div class="post-info">
                        <div class="post-text">
                            <p>{{STORY postText}}</p>
                        </div>
                    </div>
                    <div class="stats buttons" style="display: flex;">
                        <?php if ($wo['config']['second_post_button'] == 'reaction') { ?>
                            <div class="like-stat  stat-item post-like-status" style="width: inherit;">
                     <span class="like-emo post-reactions-icons-<?php echo $wo['story']['id']; ?>"
                           onclick="Wo_OpenPostReactedUsers(<?php echo $wo['story']['id']; ?>);">
                     <?php echo Wo_GetPostReactions($wo['story']['id']); ?>
                     </span>
                                <!-- <span class="like-details">Arkaprava Majumder and 1k others</span> -->
                            </div>
                        <?php } ?>
                    </div>
                    <?php if ($wo['config']['second_post_button'] == 'reaction') { ?>
                        <style>#wo_post_stat_button > .stat-item:first-child {
                                border-radius: 2em;
                            }</style>
                    <?php } ?>
                    <div class="stats" id="wo_post_stat_button">
                        <?php if ($wo['loggedin'] == true) {
                            $wo['story']['viewmode'] = "lightbox";
                            echo Wo_LoadPage('buttons/like-wonder');
                        } ?>
                    </div>
                </div>
            </div>
            <div class="comment-inner-footer lightbox-post-footer <?php echo ($wo['story']['comments_status'] == 0) ? 'hidden' : ''; ?>">
                <div id="hidden_inputbox_comment_lighbox"></div>
                <?php if ($wo['story']['post_comments'] > 3 && $wo['story']['limited_comments'] === true && $wo['story']['comments_status'] == 1) { ?>
                    <div class="view-more-wrapper load-more-comments"
                         onclick="Wo_loadAllCommentslightbox({{STORY id}});">
                        <span><?php echo $wo['lang']['view_more_comments']; ?></span>
                        <div class="ball-pulse <?php echo Wo_RightToLeft('pull-right'); ?>" style="line-height: 20px;">
                            <div></div>
                            <div></div>
                            <div></div>
                        </div>
                    </div>
                <?php } ?>
                <div class="comments-list comments-list-lightbox">
                    <div class="comment comment-container"></div>
                    <div class="comment comment-container"></div>
                    <?php
                    foreach ($wo['story']['get_post_comments'] as $wo['comment']) {
                        echo Wo_LoadPage('comment/lightbox-content');
                    }
                    ?>
                    <?php if (empty($wo['story']['get_post_comments'])) { ?>
                        <div class="lightbox-no-comments">
                            <svg version="1.1" id="Capa_1" xmlns="http://www.w3.org/2000/svg"
                                 xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 58 58"
                                 style="enable-background:new 0 0 58 58;" xml:space="preserve">
                     <g>
                         <path style="fill:#2CB742;"
                               d="M33.224,10.494H13.776C6.168,10.494,0,16.661,0,24.27v11.345c0,7.608,6.392,13.879,14,13.879h0 v7.446c0,0.503,0.384,0.755,0.74,0.4l1.521-1.521c4.116-4.116,9.699-6.325,15.52-6.325h1.443C40.832,49.494,47,43.223,47,35.615 V24.27C47,16.661,40.832,10.494,33.224,10.494z"/>
                         <g>
                             <path style="fill:#9BC0EA;"
                                   d="M44.224,0.494H24.776c-6.371,0-11.717,4.332-13.292,10.206c0.747-0.125,1.509-0.206,2.292-0.206 h19.448C40.832,10.494,47,16.661,47,24.27v11.345c0,1.259-0.183,2.476-0.5,3.639C52.957,38.061,58,32.37,58,25.615V14.27 C58,6.661,51.832,0.494,44.224,0.494z"/>
                         </g>
                         <circle style="fill:#FFFFFF;" cx="12" cy="30.494" r="3"/>
                         <circle style="fill:#FFFFFF;" cx="24" cy="30.494" r="3"/>
                         <circle style="fill:#FFFFFF;" cx="36" cy="30.494" r="3"/>
                     </g>
                  </svg>
                            <h5><?php echo TextForMode('no_comments_found'); ?></h5>
                        </div>
                    <?php } ?>
                </div>
            </div>
            <div class="lightbox-post-footer post-comments <?php echo ($wo['story']['comments_status'] == 0) ? 'hidden' : ''; ?>"
                 id="post-comments-{{STORY id}}"
                 <?php if ($wo['loggedin'] != true) { ?>onclick="location.href= '<?php echo $wo['config']['site_url']; ?>'"<?php } ?>>
                <div class="post-commet-textarea dropup">
                    <textarea class="form-control lighbox comment-textarea textarea"
                              placeholder="<?php echo TextForMode('write_comment'); ?>" type="text"
                              onkeyup="Wo_RegisterComment(this.value,{{STORY id}},{{PUBLISHER user_id}}, event, '0')"
                              onkeydown="textAreaAdjust(this, 30,'lightbox')" dir="auto"></textarea>
                    <span class="input-group-btn emo-comment dropdown-toggle" data-toggle="dropdown" role="button"
                          aria-expanded="false"
                          onclick="load_ajax_lightbox_emojii('<?php echo $wo['config']['theme_url']; ?>/emoji/');">
                  <span class="btn btn-file">
                     <svg fill="gray" height="24" viewBox="0 0 24 24" width="24" xmlns="http://www.w3.org/2000/svg"
                          class="feather feather-user-plus">
                        <path d="M0 0h24v24H0z" fill="none"/>
                        <path d="M11.99 2C6.47 2 2 6.48 2 12s4.47 10 9.99 10C17.52 22 22 17.52 22 12S17.52 2 11.99 2zM12 20c-4.42 0-8-3.58-8-8s3.58-8 8-8 8 3.58 8 8-3.58 8-8 8zm3.5-9c.83 0 1.5-.67 1.5-1.5S16.33 8 15.5 8 14 8.67 14 9.5s.67 1.5 1.5 1.5zm-7 0c.83 0 1.5-.67 1.5-1.5S9.33 8 8.5 8 7 8.67 7 9.5 7.67 11 8.5 11zm3.5 6.5c2.33 0 4.31-1.46 5.11-3.5H6.89c.8 2.04 2.78 3.5 5.11 3.5z"/>
                     </svg>
                  </span>
               </span>
                    <div class="emo-post-container dropdown-menu lightbox_real_emojiis" role="menu">

                    </div>
                </div>
            </div>
            <div class="clear"></div>
        </div>
    </div>
   </div>
</div>