<div class="wow_content wo_direct">
	<a href="<?php echo Wo_SeoLink('index.php?link1=directory'); ?>" data-ajax="?link1=directory" class="posts">
		<span><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round"><path stroke="none" d="M0 0h24v24H0z" fill="none"></path><path d="M4 5m0 1a1 1 0 0 1 1 -1h4a1 1 0 0 1 1 1v4a1 1 0 0 1 -1 1h-4a1 1 0 0 1 -1 -1z"></path><path d="M14 7l6 0"></path><path d="M14 11l6 0"></path><path d="M4 15l16 0"></path><path d="M4 19l16 0"></path></svg></span>
		<p><?php echo'Posts' ?></p>
	</a>
	<a href="<?php echo Wo_SeoLink('index.php?link1=directory-users'); ?>" data-ajax="?link1=directory-users" class="users">
		<span><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round"><path stroke="none" d="M0 0h24v24H0z" fill="none"></path><path d="M12 13a3 3 0 1 0 0 -6a3 3 0 0 0 0 6z"></path><path d="M6.201 18.744a4 4 0 0 1 3.799 -2.744h4a4 4 0 0 1 3.798 2.741"></path><path d="M19.875 6.27c.7 .398 1.13 1.143 1.125 1.948v7.284c0 .809 -.443 1.555 -1.158 1.948l-6.75 4.27a2.269 2.269 0 0 1 -2.184 0l-6.75 -4.27a2.225 2.225 0 0 1 -1.158 -1.948v-7.285c0 -.809 .443 -1.554 1.158 -1.947l6.75 -3.98a2.33 2.33 0 0 1 2.25 0l6.75 3.98h-.033z"></path></svg></span>
		<p><?php echo $wo['lang']['users'] ?></p>
	</a>
	<?php if ($wo['config']['pages'] == 1) { ?>
	<a href="<?php echo $wo['config']['site_url']; ?>/directory/pages" data-ajax="?link1=directory-pages" class="pages">
		<span><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round"><path stroke="none" d="M0 0h24v24H0z" fill="none"></path><path d="M5 14h14l-4.5 -4.5l4.5 -4.5h-14v16"></path></svg></span>
		<p><?php echo $wo['lang']['pages'] ?></p>
	</a>
	<?php } ?>
	<?php if ($wo['config']['groups'] == 1) { ?>
	<a href="<?php echo Wo_SeoLink('index.php?link1=directory-groups'); ?>" data-ajax="?link1=directory-groups" class="groups">
		<span><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round"><path stroke="none" d="M0 0h24v24H0z" fill="none"></path><path d="M10 13a2 2 0 1 0 4 0a2 2 0 0 0 -4 0"></path><path d="M8 21v-1a2 2 0 0 1 2 -2h4a2 2 0 0 1 2 2v1"></path><path d="M15 5a2 2 0 1 0 4 0a2 2 0 0 0 -4 0"></path><path d="M17 10h2a2 2 0 0 1 2 2v1"></path><path d="M5 5a2 2 0 1 0 4 0a2 2 0 0 0 -4 0"></path><path d="M3 13v-1a2 2 0 0 1 2 -2h2"></path></svg></span>
		<p><?php echo $wo['lang']['group'] ?></p>
	</a>
	<?php } ?>
	<?php if ($wo['config']['blogs'] == 1) { ?>
	<a href="<?php echo Wo_SeoLink('index.php?link1=directory-blogs'); ?>" data-ajax="?link1=directory-blogs" class="blogs">
		<span><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round"><path stroke="none" d="M0 0h24v24H0z" fill="none"></path><path d="M16 6h3a1 1 0 0 1 1 1v11a2 2 0 0 1 -4 0v-13a1 1 0 0 0 -1 -1h-10a1 1 0 0 0 -1 1v12a3 3 0 0 0 3 3h11"></path><path d="M8 8l4 0"></path><path d="M8 12l4 0"></path><path d="M8 16l4 0"></path></svg></span>
		<p><?php echo $wo['lang']['blog'] ?></p>
	</a>
	<?php } ?>
	<?php if ($wo['config']['classified'] == 1) { ?>
	<a href="<?php echo Wo_SeoLink('index.php?link1=directory-market'); ?>" data-ajax="?link1=directory-market" class="market">
		<span><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round"><path stroke="none" d="M0 0h24v24H0z" fill="none"></path><path d="M6 19m-2 0a2 2 0 1 0 4 0a2 2 0 1 0 -4 0"></path><path d="M17 19m-2 0a2 2 0 1 0 4 0a2 2 0 1 0 -4 0"></path><path d="M17 17h-11v-14h-2"></path><path d="M6 5l14 1l-1 7h-13"></path></svg></span>
		<p><?php echo $wo['lang']['market'] ?></p>
	</a>
	<?php } ?>
	<?php if ($wo['config']['events'] == 1) { ?>
	<a href="<?php echo Wo_SeoLink('index.php?link1=directory-events'); ?>" data-ajax="?link1=directory-events" class="events">
		<span><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round"><path stroke="none" d="M0 0h24v24H0z" fill="none"></path><path d="M4 5m0 2a2 2 0 0 1 2 -2h12a2 2 0 0 1 2 2v12a2 2 0 0 1 -2 2h-12a2 2 0 0 1 -2 -2z"></path><path d="M16 3l0 4"></path><path d="M8 3l0 4"></path><path d="M4 11l16 0"></path><path d="M8 15h2v2h-2z"></path></svg></span>
		<p><?php echo $wo['lang']['events'] ?></p>
	</a>
	<?php } ?>
	<?php if ($wo['config']['games'] == 1 && $wo['config']['can_use_games']) { ?>
	<a href="<?php echo Wo_SeoLink('index.php?link1=directory-games'); ?>" data-ajax="?link1=directory-games" class="games">
		<span><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round"><path stroke="none" d="M0 0h24v24H0z" fill="none"></path><path d="M12 5h3.5a5 5 0 0 1 0 10h-5.5l-4.015 4.227a2.3 2.3 0 0 1 -3.923 -2.035l1.634 -8.173a5 5 0 0 1 4.904 -4.019h3.4z"></path><path d="M14 15l4.07 4.284a2.3 2.3 0 0 0 3.925 -2.023l-1.6 -8.232"></path><path d="M8 9v2"></path><path d="M7 10h2"></path><path d="M14 10h2"></path></svg></span>
		<p><?php echo $wo['lang']['games'] ?></p>
	</a>
	<?php } ?>
	<?php if ($wo['config']['forum'] == 1) { ?>
	<a href="<?php echo Wo_SeoLink('index.php?link1=directory-forums'); ?>" data-ajax="?link1=directory-forums" class="forums">
		<span><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round"><path stroke="none" d="M0 0h24v24H0z" fill="none"></path><path d="M21 14l-3 -3h-7a1 1 0 0 1 -1 -1v-6a1 1 0 0 1 1 -1h9a1 1 0 0 1 1 1v10"></path><path d="M14 15v2a1 1 0 0 1 -1 1h-7l-3 3v-10a1 1 0 0 1 1 -1h2"></path></svg></span>
		<p><?php echo $wo['lang']['forum'] ?></p>
	</a>
	<?php } ?>
	<?php if ($wo['config']['movies'] == 1 && $wo['config']['can_use_movies']) { ?>
	<a href="<?php echo Wo_SeoLink('index.php?link1=directory-movies'); ?>" data-ajax="?link1=directory-movies" class="movies">
		<span><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round"><path stroke="none" d="M0 0h24v24H0z" fill="none"></path><path d="M4 4m0 2a2 2 0 0 1 2 -2h12a2 2 0 0 1 2 2v12a2 2 0 0 1 -2 2h-12a2 2 0 0 1 -2 -2z"></path><path d="M8 4l0 16"></path><path d="M16 4l0 16"></path><path d="M4 8l4 0"></path><path d="M4 16l4 0"></path><path d="M4 12l16 0"></path><path d="M16 8l4 0"></path><path d="M16 16l4 0"></path></svg></span>
		<p><?php echo $wo['lang']['movies'] ?></p>
	</a>
	<?php } ?>
	<?php if ($wo['config']['job_system'] == 1) { ?>
	<a href="<?php echo Wo_SeoLink('index.php?link1=directory-jobs'); ?>" data-ajax="?link1=directory-jobs" class="jobs">
		<span><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round"><path stroke="none" d="M0 0h24v24H0z" fill="none"></path><path d="M3 7m0 2a2 2 0 0 1 2 -2h14a2 2 0 0 1 2 2v9a2 2 0 0 1 -2 2h-14a2 2 0 0 1 -2 -2z"></path><path d="M8 7v-2a2 2 0 0 1 2 -2h4a2 2 0 0 1 2 2v2"></path><path d="M12 12l0 .01"></path><path d="M3 13a20 20 0 0 0 18 0"></path></svg></span>
		<p><?php echo $wo['lang']['jobs'] ?></p>
	</a>
	<?php } ?>
	<?php if ($wo['config']['funding_system'] == 1) { ?>
	<a href="<?php echo Wo_SeoLink('index.php?link1=directory-fundings'); ?>" data-ajax="?link1=directory-fundings" class="funding">
		<span><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round"><path stroke="none" d="M0 0h24v24H0z" fill="none"></path><path d="M19.5 12.572l-7.5 7.428l-7.5 -7.428a5 5 0 1 1 7.5 -6.566a5 5 0 1 1 7.5 6.572"></path><path d="M12 6l-3.293 3.293a1 1 0 0 0 0 1.414l.543 .543c.69 .69 1.81 .69 2.5 0l1 -1a3.182 3.182 0 0 1 4.5 0l2.25 2.25"></path><path d="M12.5 15.5l2 2"></path><path d="M15 13l2 2"></path></svg></span>
		<p><?php echo $wo['lang']['funding'] ?></p>
	</a>
	<?php } ?>
</div>