<style>
@font-face {
    font-family: OpenSansLight;
    src: url("<?php echo $wo['config']['theme_url'];?>/fonts/OpenSansLight/OpenSansLight.woff") format("woff");
    font-weight: normal;
}
@font-face {
    font-family: OpenSansRegular;
    src: url("<?php echo $wo['config']['theme_url'];?>/fonts/OpenSansRegular/OpenSansRegular.woff") format("woff");
    font-weight: normal;
}
@font-face {
    font-family: OpenSansSemiBold;
    src: url("<?php echo $wo['config']['theme_url'];?>/fonts/OpenSansSemiBold/OpenSansSemiBold.woff") format("woff");
    font-weight: normal;
}
@font-face {
    font-family: OpenSansBold;
    src: url("<?php echo $wo['config']['theme_url'];?>/fonts/OpenSansBold/OpenSansBold.woff") format("woff");
    font-weight: normal;
}
@font-face {
    font-family: Gilroy-ExtraBold;
    src: url("<?php echo $wo['config']['theme_url'];?>/fonts/Gilroy-ExtraBold.otf") format("opentype");
    font-weight: normal;
}
@font-face {
    font-family: Vodafone Rg;
    src: url("<?php echo $wo['config']['theme_url'];?>/fonts/vodafone.ttf") format("truetype");
    font-weight: normal;
}
@font-face {
    font-family: Vodafone ExB;
    src: url("<?php echo $wo['config']['theme_url'];?>/fonts/VodafoneExBd.ttf") format("truetype");
    font-weight: normal;
}
:root {
	--plyr-color-main: <?php echo $wo['config']['btn_background_color'];?> ;
	--main-color: <?php echo $wo['config']['btn_background_color'];?> ;
}

.icon_main {
	stroke: <?php echo $wo['config']['btn_background_color'];?>;
}

.wo_page_profile .options-buttons .btn.btn-success, .wo_page_profile .options-buttons .btn.btn-info, .wo_vew_apld_msg .btn {
	color: <?php echo $wo['config']['btn_background_color'];?>;
}
.wo_page_profile .options-buttons .btn.btn-success:hover, .wo_page_profile .options-buttons .btn.btn-info:hover, .wo_vew_apld_msg .btn:hover, .right_user_info .flex_stats li .badge {
	background: <?php echo $wo['config']['btn_background_color'];?>;
	color: <?php echo $wo['config']['btn_color'];?>;
}

#wo_sidebar_users .btn-default.wo_follow_btn .icon_main {
	stroke: <?php echo $wo['config']['btn_background_color'];?> !important;
}
.icon_main_fill {
	fill: <?php echo $wo['config']['btn_background_color'];?>;
}
.wo_follow_btn {
    background: <?php echo $wo['config']['btn_background_color'];?> !important;
}

.user-status-home ul.status-list li.create_new .avatar:before {
    background: linear-gradient(135.87deg, <?php echo $wo['config']['btn_background_color'];?> 1.25%, #3F4354 51.73%, rgba(198, 77, 83, 0.17) 77.22%);
}
.go_pro_table_background .plan_foot .btn {
	color: <?php echo $wo['config']['btn_background_color'];?>;
}
.select_radio_btn .sr_btn_lab_innr:hover, .select_radio_btn label > input:checked ~ .sr_btn_lab_innr {
	box-shadow: 0px 0px 0px 2px <?php echo $wo['config']['btn_background_color'];?> !important;
}
.select_radio_btn label > input:checked ~ .sr_btn_lab_innr > span {
    color: <?php echo $wo['config']['btn_background_color'];?> !important;
}

@media (min-width: 992px) {
::-webkit-scrollbar-thumb {
    background: <?php echo $wo['config']['btn_background_color'];?>;
}
}

.wo_prof_des_toggle .round-check input:checked+label {
	border-color: <?php echo $wo['config']['btn_background_color'];?>;
}
.wo_prof_des_toggle .round-check input:checked+label span {
	color: <?php echo $wo['config']['btn_background_color'];?>;
	background: transparent;
}

.chat-messages-wrapper .message.wo_msg_prod_prnt .product-price, .message-contnaier .wo_msg_prod_prnt .product-price {
	color: <?php echo $wo['config']['btn_background_color'];?>;
}

.pagination>.active>a, .pagination>.active>a:focus, .pagination>.active>a:hover, .pagination>.active>span, .pagination>.active>span:focus, .pagination>.active>span:hover {
	background: <?php echo $wo['config']['btn_background_color'];?>;
	color: <?php echo $wo['config']['btn_color'];?>;
}

.wow_htag a svg {
    color:  <?php echo $wo['config']['btn_background_color'];?> !important;
}
.wo_follow_btn:hover {
    background: <?php echo $wo['config']['btn_hover_background_color'];?> !important;
}
.wo_following_btn {
	background: <?php echo $wo['config']['btn_background_color'];?> !important;
}
.wo_following_btn:hover {
	background: <?php echo $wo['config']['btn_hover_background_color'];?> !important;
}
#progress .progress, #percent, .load-more .btn, .wow_price_plan .plan_body p svg {
	color: <?php echo $wo['config']['btn_background_color'];?>;
}
.fund_raise_bar .progress .progress-bar, .fundings_footer .progress .progress-bar {
	background: <?php echo $wo['config']['btn_background_color'];?>;
}
.go_pro_table_background, .go_pro_table_background .main, .go_pro_table_background .plan_body p svg, .messages-recipients-list.active .messages-user-name, .messages-recipients-list.active .msg_rght_prt > .user_nname, .messages-recipients-list.active .messages-last-sent {
	color: <?php echo $wo['config']['btn_color'];?> !important;
}
.go_pro_table_background:before {
    background-color: <?php echo $wo['config']['btn_background_color'];?>;
}

.friends_nearby_status_ul li.active, #search-nearby-users .nearby-users-gender-collapse ul li.active, .wow_srch_innr_filtr .round_check input:checked+label {
	color: <?php echo $wo['config']['btn_color'];?>;
    background-color: <?php echo $wo['config']['btn_background_color'];?>;
}

input.cusrange[type=range]::-webkit-slider-thumb {
    background-color: <?php echo $wo['config']['btn_background_color'];?>;
    box-shadow: none;
}



.navbar-default {
    background: #fff; border: none;
    height: 70px;box-shadow: 0 1px 6px rgb(0 0 0 / 5%);
}

.round-check input[type="checkbox"]:checked + label:before, .round-check input[type="radio"]:checked + label:before {
    background: <?php echo $wo['config']['btn_background_color'];?> !important;
}
.group-messages-wrapper a{
    color: <?php echo $wo['config']['btn_background_color'];?> !important;
}
ul.profile-completion-bar li.completion-bar div.completion-bar-status {
    background: <?php echo $wo['config']['btn_background_color'];?> !important;
}
.wow_big_head_link ul li.active a, #wo_nw_msg_page .msg_under_hood .mobilerightpane .messages-search-users-form .wo_msg_tabs li.active a, .messages-recipients-list.active {
  background: <?php echo $wo['config']['btn_background_color'];?>;
  color: <?php echo $wo['config']['btn_color'];?>;
}
.wo_chat_tabs li.active a {
  background: <?php echo $wo['config']['btn_background_color'];?> !important;
  color: <?php echo $wo['config']['btn_color'];?> !important;
}
.result-bar {
    background: <?php echo $wo['config']['btn_background_color'];?> !important;
}
.featured-users {
	background: <?php echo $wo['config']['btn_background_color'];?>;
  color: <?php echo $wo['config']['btn_color'];?>;
}
.featured-users .sidebar-title-back, .featured-users .pro-me-here, .wo_pro_users li .user span {
    color: <?php echo $wo['config']['btn_color'];?> !important;
}

.lang_select_modal .language_info {
    background: <?php echo $wo['config']['btn_background_color'];?>
}
.lang_select_modal .language_info h3 {
	color: <?php echo $wo['config']['btn_color'];?>;
}



.avtive {
    border-color: <?php echo $wo['config']['btn_background_color'];?> !important;
}

.new-update-alert {
    background: <?php echo $wo['config']['btn_hover_background_color'];?>;
	color: <?php echo $wo['config']['btn_color'];?>;
}

#wo_nw_msg_page .msg_under_hood .mobilerightpane .messages-search-users-form .inner-addon .btn_contr {
	background: <?php echo $wo['config']['btn_background_color'];?>;
	color: <?php echo $wo['config']['btn_color'];?>;
}
#wo_nw_msg_page .msg_under_hood .mobilerightpane .messages-search-users-form .inner-addon button.btn {
	color: <?php echo $wo['config']['btn_color'];?>;
}
#wo_nw_msg_page .msg_under_hood .mobilerightpane .messages-search-users-form .inner-addon button.btn:hover {
	background: <?php echo $wo['config']['btn_hover_background_color'];?>;
}

.green-audio-player svg path {
	fill: <?php echo $wo['config']['btn_background_color'];?>;
}
.green-audio-player .slider .gap-progress, .green-audio-player .slider .gap-progress .pin {
	background-color: <?php echo $wo['config']['btn_background_color'];?> !important;
}

.add_as_cont_list label input:checked+div {
    background-color: <?php echo $wo['config']['btn_background_color'];?>;
    color: <?php echo $wo['config']['btn_color'];?>;
}

.barloading {
  background-color: rgb(165 39 41 / 6%) !important;
}
.barloading:before {
    background-color: <?php echo $wo['config']['btn_background_color'];?>;
}
.left-sidebar ul li a i {
    color: <?php echo $wo['config']['btn_background_color'];?> !important;
}
.cs-loader-inner, .main  {
    color: <?php echo $wo['config']['btn_background_color'];?>;
}
.login input:focus, ul.profile-completion-bar li.completion-bar div.completion-bar-wrapper, .edit_grp_info_modal input.form-control:not(textarea):focus, .verfy_sett_email_phone input.form-control:not(textarea):focus {
    border-color: <?php echo $wo['config']['btn_background_color'];?> !important;
}
.login:not(.loading) button:hover {
    background: <?php echo $wo['config']['btn_hover_background_color'];?> !important;
    color: <?php echo $wo['config']['btn_color'];?>;
}
.wo_setting_sidebar ul .list-group-item{
    background: <?php echo $wo['config']['btn_background_color'];?> !important;
}
.wo_setting_sidebar ul .list-group-item a{
    color: <?php echo $wo['config']['btn_color'];?>;
}
.wo_settings_page .setting-panel input[type=text]:focus, .wo_settings_page .setting-panel input[type=email]:focus, .wo_settings_page .setting-panel input[type=password]:focus, .wo_settings_page .setting-panel select:focus, .wo_settings_page .setting-panel textarea:focus {
    border-color: #03A9F4;
}

#search-nearby-users .nearby-users-relationship-collapse li.active .friends_toggle{
    border-color: <?php echo $wo['config']['btn_background_color'];?>;
}
#search-nearby-users .nearby-users-relationship-collapse li.active .friends_toggle:after{
    background: <?php echo $wo['config']['btn_background_color'];?>;
}
.wo_page_hdng_menu > ul li.active a {
    box-shadow: inset 0px -2.5px <?php echo $wo['config']['btn_background_color'];?>;
}
.login button, .postCategory h5, .wo_search_page .nav-tabs li.active a {
    background: <?php echo $wo['config']['btn_background_color'];?> !important;
    color: <?php echo $wo['config']['btn_color'];?> !important;
}
.mejs-controls .mejs-time-rail .mejs-time-current, .mejs-controls .mejs-horizontal-volume-slider .mejs-horizontal-volume-current, .mejs-controls .mejs-volume-button .mejs-volume-slider .mejs-volume-current {
    background-color: <?php echo $wo['config']['btn_background_color'];?> !important;
    background: <?php echo $wo['config']['btn_background_color'];?> !important;
    background-image: <?php echo $wo['config']['btn_background_color'];?> !important;
}
.navbar-default .navbar-nav>.open>a, .navbar-default .navbar-nav>.open>a:focus, .navbar-default .navbar-nav>.open>a:hover {
    background-color: #f4f4f4 !important;
}
.navbar-default .navbar-nav>.active>a, .navbar-default .navbar-nav>.active>a:focus, .navbar-default .navbar-nav>.active>a:hover, .nav-names li:hover {
    color: <?php echo $wo['config']['header_color'];?> !important;
    background-color: <?php echo $wo['config']['header_hover_border'];?> !important;
}
body {
    background-color: <?php echo $wo['config']['body_background'];?>;
}
.navbar-default .navbar-nav>li>a {
    color: #222;
    font-size: 13px;
	height: auto;padding-top: 18px;
    padding-bottom: 18px;
}

.btn-main, .wo_following_btn {
    color: <?php echo $wo['config']['btn_color'];?>;
    background-color: <?php echo $wo['config']['btn_background_color'];?>;
    border-color: <?php echo $wo['config']['btn_background_color'];?>;
}
.btn-main:hover, .wo_following_btn:hover {
    color: <?php echo $wo['config']['btn_hover_color'];?>;
    background-color: <?php echo $wo['config']['btn_hover_background_color'];?>;
    border-color: <?php echo $wo['config']['btn_hover_background_color'];?>;
}

.wow_mat_mdl .modal-footer .btn.main {
    color: <?php echo $wo['config']['btn_color'];?> !important;
    background-color: <?php echo $wo['config']['btn_background_color'];?>;
}
.wow_mat_mdl .modal-footer .btn.main:hover {
    color: <?php echo $wo['config']['btn_hover_color'];?> !important;
    background-color: <?php echo $wo['config']['btn_hover_background_color'];?>;
}

.sun_pub_privacy_menu li label input[type="radio"]:checked+span{
	color: <?php echo $wo['config']['btn_color'];?>;
    background: <?php echo $wo['config']['btn_background_color'];?>;
}

#wo_home_btns.btn-main {
	 color: <?php echo $wo['config']['btn_color'];?> !important;
}

.wow_pops_head {
    /*background: <?php echo $wo['config']['btn_hover_background_color'];?>;*/
}
.btn-main:focus {
	color: <?php echo $wo['config']['btn_hover_color'];?>;
}
.active-wonder {
    color: <?php echo $wo['config']['btn_background_color'];?>;
}
.admin-panel .col-md-9 .list-group-item:first-child, .setting-panel .col-md-8 .list-group-item:first-child, .profile-lists .list-group-item:first-child, .col-md-8 .list-group-item:first-child, .col-md-3.custom .list-group-item:first-child, .col-sm-4 .list-group-item:first-child, .col-md-7 .list-group-item:first-child, .col-md-9 .list-group-item:first-child, .red-list .list-group-item:first-child, .active.list-group-item:first-child {
     color: #444;
     background-color: #fcfcfc;
     border-bottom: 1px solid #f1f1f1;
     padding: 18px;
}
.admin-panel .col-md-9 .list-group-item:first-child a, .setting-panel .col-md-8 .list-group-item:first-child a, .profile-lists .list-group-item:first-child a, .col-md-8 .list-group-item:first-child a, .col-md-7 .list-group-item:first-child a, .active.list-group-item:first-child a {
    color: #444 !important;
}
.list-group-item.black-list.active-list, .red-list.active-list {
    color: <?php echo $wo['config']['btn_color'];?>;
    background-color: <?php echo $wo['config']['btn_background_color'];?>;
}
.list-group-item.black-list {
    background: <?php echo $wo['config']['btn_background_color'];?>;
}
.profile-top-line {
    background-color: <?php echo $wo['config']['btn_background_color'];?>;
}
#bar {
    background-color: <?php echo $wo['config']['btn_background_color'];?>;
}
.list-group-item.black-list a{
    color: <?php echo $wo['config']['btn_color'];?>;
}
.list-group-item.black-list.active-list a{
    color: <?php echo $wo['config']['btn_background_color'];?>;
}
.main-color, .small-text a, .show-message-link-container a, .search-advanced-container a {
    color: <?php echo $wo['config']['btn_background_color'];?> !important;
}
.nav-tabs>li.active>a, .nav-tabs>li.active>a:focus, .nav-tabs>li.active>a:hover {
    color: <?php echo $wo['config']['btn_color'];?>;
    cursor: default;
    color: <?php echo $wo['config']['btn_background_color'];?>;
    border-bottom: 1px solid <?php echo $wo['config']['btn_background_color'];?>;
    background-color: transparent
}
.btn-active {
    color: <?php echo $wo['config']['btn_color'];?>;
    background: <?php echo $wo['config']['btn_background_color'];?>;
    outline: none;
    border: 1px solid <?php echo $wo['config']['btn_background_color'];?>
}
.btn-active:hover, .btn-active:focus {
    border: 1px solid <?php echo $wo['config']['btn_hover_background_color'];?>;
    color: <?php echo $wo['config']['btn_hover_color'];?>;
    background: <?php echo $wo['config']['btn_hover_background_color'];?>;
}
.btn-active-color:hover {
    background: <?php echo $wo['config']['btn_hover_background_color'];?>;
}

.chat-tab .chat-textarea .chat-btns-w .chat_optns {
    color: <?php echo $wo['config']['btn_background_color'];?>;
    fill: <?php echo $wo['config']['btn_background_color'];?>;
}

.profile-style .user-follow-button button.btn-active, .btn-login, .btn-register {
    background: <?php echo $wo['config']['btn_background_color'];?>;
    color: <?php echo $wo['config']['btn_color'];?>;
}
.profile-style .user-follow-button button.btn-active:hover, .btn-login:hover, .btn-login:focus, .btn-register:hover, .btn-register:focus {
    color: <?php echo $wo['config']['btn_hover_color'];?>;
    background: <?php echo $wo['config']['btn_hover_background_color'];?>;
}
.panel-login>.panel-heading a.active {
    color: <?php echo $wo['config']['btn_background_color'];?>;
    font-size: 18px;
}
.hash {
    color: <?php echo $wo['config']['btn_background_color'];?>;
}
.message-text .hash {
    color: #fff !important;
}
.search-container .search-input {
    color: #222 !important;
    background: #F2F2F2 !important;
}
.chat-messages-wrapper .outgoing .message-text {
    background: <?php echo $wo['config']['btn_background_color'];?>;
    color: <?php echo $wo['config']['btn_color'];?>;
}
.normal-container {
    width: 100%;
    height: 100%;
    margin-top: 15px;
}
.active.fa-thumbs-up {
    color: <?php echo $wo['config']['btn_background_color'];?>;
}
.api-ex-urls {
    background-color: <?php echo $wo['config']['btn_background_color'];?>; color: <?php echo $wo['config']['btn_color'];?>;
}
.user-username {
    color: <?php echo $wo['config']['btn_background_color'];?>;
}
.upload-image {
    border: 3px dashed <?php echo $wo['config']['btn_background_color'];?>;
}
.events-tab-list li { background-color: <?php echo $wo['config']['btn_background_color'];?>; }
.events-tab-list li:hover { background-color: <?php echo $wo['config']['btn_background_color'];?>; }
.active-e-tab { background-color: <?php echo $wo['config']['btn_background_color'];?> !important; }
.main { color: <?php echo $wo['config']['btn_background_color'];?> !important; }
.events-list-dropup-menu ul li a:hover { background: <?php echo $wo['config']['btn_background_color'];?>; }
.usr-offline { color: <?php echo $wo['config']['btn_background_color'];?>; }
.blog-dd-ul li span:hover, .blog-dd-ul li a:hover { background: <?php echo $wo['config']['btn_background_color'];?> !important; }
.blog_publ {background: <?php echo $wo['config']['btn_background_color'];?> ; border: 1px solid <?php echo $wo['config']['btn_background_color'];?> ; }
.slide-film-desc:hover, .movies-top-breadcrumb li:hover, .movies-top-breadcrumb li a:hover{
    color: <?php echo $wo['config']['btn_background_color'];?> !important;
}
.movies h3.latest-movies, h3.recommended-movies {
    border-left: 3px solid  <?php echo $wo['config']['btn_background_color'];?>;
}

.ads-navbar-wrapper ul li a.active {
	color: <?php echo $wo['config']['btn_background_color'];?>;
}
.wo_page_hdng_innr span {
	background-color: <?php echo $wo['config']['btn_background_color'];?>;
	color: <?php echo $wo['config']['btn_color'];?>;
}

.wow_creads_minstp .line .line_sec {
    background: <?php echo $wo['config']['btn_background_color'];?>;
}

.step-one-active.wow_creads_minstp .dot.one {background: <?php echo $wo['config']['btn_background_color'];?> !important;}
.step-two-active.wow_creads_minstp .dot.one, .step-three-active.wow_creads_minstp .dot.one {background: <?php echo $wo['config']['btn_background_color'];?> !important;}
.step-two-active.wow_creads_minstp .dot.two, .step-three-active.wow_creads_minstp .dot.two {background: <?php echo $wo['config']['btn_background_color'];?> !important;}
.step-three-active.wow_creads_minstp .dot.three {background: <?php echo $wo['config']['btn_background_color'];?>;}

.step-one-active .steps > .step-one, .step-two-active .steps > .step-one, .step-two-active .steps > .step-two, .step-three-active .steps > .step-one, .step-three-active .steps > .step-two, .step-three-active .steps > .step-three {
	color: <?php echo $wo['config']['btn_background_color'];?>;
}


.btn-loading:after {
	background-color: <?php echo $wo['config']['btn_background_color'];?>;
}
.wow_pub_privacy_menu li label input[type="radio"]:checked+span {
	background-color: <?php echo $wo['config']['btn_background_color'];?>;color: <?php echo $wo['config']['btn_color'];?>;
}
.order_by ul li.active a {background: <?php echo $wo['config']['btn_background_color'];?> !important;color: <?php echo $wo['config']['btn_color'];?> !important;}


<?php
if ($wo['config']['chatSystem'] == 1 && $wo['page'] != 'get_news_feed' && $wo['page'] != 'welcome' && $wo['loggedin'] == true && $wo['page'] != 'messages') { ?>
body, .navbar-default, .wo_about_wrapper_parent{padding-right: 75px;}
.wow_main_float_head {right: 75px;}
@media (max-width:1140px){
	.wo_about_wrapper_parent{padding-right: 0px;}
	.wow_main_float_head {right: 0;}
}
<?php } ?>

<?php if($wo['language_type'] == 'rtl' && $wo['config']['chatSystem'] == 1 && $wo['page'] != 'get_news_feed' && $wo['page'] != 'welcome' && $wo['page'] != 'messages' && $wo['loggedin'] == true) { ?>
body, .navbar-default, .wo_about_wrapper_parent{padding-left: 75px;padding-right: 0px;}
.wow_main_float_head {right: 0;left: 75px;}
@media (max-width:1140px){
	.wo_about_wrapper_parent{padding-left: 0px;}
	.wow_main_float_head {right: 0;left: 0;}
}
<?php } ?>

#welcomeheader .mdbtn:hover{background-color: <?php echo $wo['config']['header_color'];?>;color: <?php echo $wo['config']['header_background'];?>;border-color: <?php echo $wo['config']['header_color'];?>;}

.post .panel.active_shadow {
    box-shadow: 0 0 0 1.5px <?php echo $wo['config']['btn_background_color'];?> !important;
}

.ui-widget-header .ui-state-default, .wo_adv_search_filter_side .ui-slider .ui-slider-range, .wo_adv_search_filter_side .ui-slider .ui-slider-handle {
    background-color: <?php echo $wo['config']['btn_background_color'];?>;
}
<?php
if (!empty($wo['reactions_types'])) {
    foreach ($wo['reactions_types'] as $key => $value) {
?>
.reaction-<?php echo $value['id'];?>::before {
    content: "<?php echo $value['name'];?>";
}
<?php } } ?>
/*.reaction-like::before {
    content: "<?php echo $wo['lang']['like'];?>";
}
.reaction-love::before {
    content: "<?php echo $wo['lang']['love'];?>";
}
.reaction-haha::before {
    content: "<?php echo $wo['lang']['haha'];?>";
}
.reaction-wow::before {
    content: "<?php echo $wo['lang']['wow'];?>";
}
.reaction-sad::before {
    content: "<?php echo $wo['lang']['sad'];?>";
}
.reaction-angry::before {
    content: "<?php echo $wo['lang']['angry'];?>";
}*/

.text-sender-container .msg_usr_info_top_list .msg_usr_cht_opts_btns > span:hover, .text-sender-container .msg_usr_info_top_list .msg_usr_cht_usr_data a:hover {
    color: <?php echo $wo['config']['btn_background_color'];?>;
}
.text-sender-container .outgoing .message-model .message {background-color: <?php echo $wo['config']['btn_background_color'];?>;color: <?php echo $wo['config']['btn_color'];?>;}
.text-sender-container .outgoing .message-model .message p, .text-sender-container .outgoing .message-model .message a {color: <?php echo $wo['config']['btn_color'];?>;}

<?php if ($wo['config']['google_map'] == 0 && $wo['config']['yandex_map'] == 0) { ?>
/*#filterby-post li {
    width: 16.5%;
}*/
<?php }?>
</style>