<div class="page-margin">
	<div class="row">
		<div class="col-md-2 leftcol"><?php echo Wo_LoadPage("sidebar/left-sidebar"); ?></div>
		<div class="col-md-7 middlecol">
			<form class="create-page-form form-horizontal" method="post">
				<div class="page-margin mt-0">
					<div class="wow_content popular_posts_hdr flex">
						<h2>&nbsp;<?php echo $wo['lang']['create_new_page'];?></h2>
						<div class="btnss">
							<a class="btn btn-mat btn-default" data-ajax="?link1=pages" href="<?php echo Wo_SeoLink('index.php?link1=pages');?>"><?php echo $wo['lang']['cancel'];?></a>
							<button class="btn btn-main btn-mat add_wow_loader" type="submit"><?php echo $wo['lang']['create']; ?></button>
						</div>
					</div>
				</div>
			
				<div class="page-margin wow_content wow_sett_content">
					<div class="app-general-alert setting-update-alert"></div>
					
					<div class="wow_form_fields">
						<label for="page_title"><?php echo $wo['lang']['page_name']; ?></label>
						<input id="page_title" name="page_title" type="text">
						<span class="help-block"><?php echo $wo['lang']['your_page_title'];?></span>
					</div>
					<div class="wow_form_fields">
						<label for="page_name"><?php echo $wo['lang']['page'];?> URL</label>
						<div class="input-group">
							<span class="input-group-addon"><?php echo $wo['config']['site_url'];?>/</span>
							<input id="page_name" name="page_name" type="text">
						</div>
					</div>
					<div class="wow_form_fields">
						<label for="page_category"><?php echo $wo['lang']['page_category']; ?></label>
						<select name="page_category" id="page_category" onchange="GetPageSubCategory(this)">
							<?php foreach ($wo['page_categories'] as $category_id => $category_name) {?>
								<option value="<?php echo $category_id?>"><?php echo $category_name; ?></option>
							<?php } ?>
						</select>
					</div>
					<?php if (!empty($wo['page_sub_categories'])) { ?>
					<div class="wow_form_fields">
						<label for="page_sub_category"><?php echo $wo['lang']['sub_category']; ?></label>
						<select name="page_sub_category" id="page_sub_category">
							<?php
							if (!empty($wo['page_sub_categories'][array_keys($wo['page_categories'])[0]])) {
							foreach ($wo['page_sub_categories'][array_keys($wo['page_categories'])[0]] as $id => $sub_category) { ?>
								<option value="<?php echo $sub_category['id']?>"><?php echo $sub_category['lang']; ?></option>
							<?php } } ?>
						</select>
					</div>
				    <?php } ?>
					<div class="wow_form_fields">
						<label for="page_description"><?php echo $wo['lang']['page_description']; ?></label>
						<textarea name="page_description" id="page_description" rows="3"></textarea>
						<span class="help-block"><?php echo $wo['lang']['page_description_info'];?></span>
					</div>
					<?php $fields = Wo_GetCustomFields('page'); 
					if (!empty($fields)) {
						foreach ($fields as $key => $wo['field']) {
							echo Wo_LoadPage('page/fields');
						}
					}
					?>
				  	
					<input type="hidden" name="hash_id" value="<?php echo Wo_CreateSession();?>">
				</div>
			</form>
		</div>
		<!-- .col-md-8 -->
		<?php echo Wo_LoadPage('sidebar/content');?>
	</div>
   <!-- .row -->
</div>
<!-- .page-margin -->
<script type="text/javascript">
	<?php 
$js_array = json_encode($wo['page_sub_categories']);
echo "var sub_categories_array = ". $js_array . ";\n";
?>
	function GetPageSubCategory(self) {
		id = $(self).val();
		var text = "";
		if (typeof(sub_categories_array[id]) == 'undefined') {
		    $('#page_sub_category').html('');
		}
		else{
		   	sub_categories_array[id].forEach(function(entry) {
				text = text + "<option value='"+entry.id+"'>"+entry.lang+"</option>";
			});
		    $('#page_sub_category').html(text);
		}
	}
   $(function() {
     $('form.create-page-form').ajaxForm({
       url: Wo_Ajax_Requests_File() + '?f=pages&s=create_page',
       beforeSend: function() {
         $('.create-page-form').find('.add_wow_loader').addClass('btn-loading');
       },
       success: function(data) {
         scrollToTop();
         if (data.status == 200) {
           window.location.href = data.location;
         } else {
             var errors = data.errors.join("<br>");
             $('.app-general-alert').html('<div class="alert alert-danger">' + errors + '</div>');
             $('.alert-danger').fadeIn(300);
         }
         $('.create-page-form').find('.add_wow_loader').removeClass('btn-loading');
       }
     });
   });
</script>