<div class="cool-style-album profi_groups user_list col-xs-6 col-sm-6 col-lg-4" id="invite-<?php echo $wo['UsersList']['user_id']?>" data-user-id="<?php echo $wo['UsersList']['user_id'];?>">
	<div class="wow_content album_parent">
		<div class="avatar">
			<a href="<?php echo $wo['UsersList']['url'];?>" data-ajax="?link1=timeline&u=<?php echo $wo['UsersList']['username']?>">
				<img src="<?php echo $wo['UsersList']['avatar'];?>" alt="<?php echo $wo['UsersList']['name']; ?> Profile Picture" />
			</a>
		</div>
		<div class="album-name">
			<a href="<?php echo $wo['UsersList']['url'];?>" data-ajax="?link1=timeline&u=<?php echo $wo['UsersList']['username']?>"><h4><?php echo $wo['UsersList']['name']; ?></h4></a>
			
			<?php if($wo['config']['user_lastseen'] == 1 && $wo['UsersList']['showlastseen'] != 0): ?>
				<p>
					<?php echo Wo_UserStatus($wo['UsersList']['user_id'],$wo['UsersList']['lastseen']); ?>
				</p>
			<?php endif; ?>
		</div>
		<div class="user-follow-button">
			<button type="button" onclick="Wo_RegisterInvite(<?php echo $wo['UsersList']['user_id'];?>, <?php echo $wo['page_profile']['page_id'];?>)" class="btn btn-main btn-sm" id="wo_useract_btn">
				<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-user-plus"><path d="M16 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2"></path><circle cx="8.5" cy="7" r="4"></circle><line x1="20" y1="8" x2="20" y2="14"></line><line x1="23" y1="11" x2="17" y2="11"></line></svg>
				<span class="button-text"> <?php echo $wo['lang']['invite'];?></span>
			</button>
		</div>
	</div>
</div>