<div class="post-container sun_post job_apply" data-job-apply="<?php echo($wo['job_apply']['id']) ?>">
	<div class="wow_content">
		<div class="wo_vew_apld_jobs">
			<div class="wo_vew_apld_head">
				<div class="avatar">
					<a href="<?php echo  $wo['job_apply']['user_data']['url']; ?>" data-ajax="?link1=timeline&u=<?php echo $wo['job_apply']['user_data']['username']?>">
						<img src="<?php echo $wo['job_apply']['user_data']['avatar'] ; ?>" id="updateImage-<?php echo $wo['job_apply']['user_data']['user_id']?>" alt="<?php echo $wo['job_apply']['user_data']['username']; ?>">
					</a>
				</div>
				<div class="jinfo">
					<?php if (!empty($wo['job_apply']['user_name'])) { ?>
						<h4><?php echo $wo['job_apply']['user_name']; ?></h4>
					<?php } ?>
					<div class="row">
						<?php if (!empty($wo['job_apply']['location'])) { ?>
							<div class="col-md-5">
								<p class="wo_vew_apld_ico"><svg width="14" height="14" viewBox="0 0 14 14" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M12.3327 6.45032C12.3327 9.46045 9.94487 13 6.99935 13C4.05383 13 1.66602 9.46045 1.66602 6.45032C1.66602 3.44019 4.05383 1 6.99935 1C9.94487 1 12.3327 3.44019 12.3327 6.45032Z" stroke="currentColor" stroke-width="1.5"></path><path d="M5.33398 6.00016C5.33398 5.07969 6.08018 4.3335 7.00065 4.3335C7.92113 4.3335 8.66732 5.07969 8.66732 6.00016C8.66732 6.92064 7.92113 7.66683 7.00065 7.66683C6.08018 7.66683 5.33398 6.92064 5.33398 6.00016Z" class="icon_main" stroke-width="1.5"></path></svg> <?php echo $wo['job_apply']['location']; ?></p>
							</div>
						<?php } ?>
						<div class="col-md-7">
							<p class="wo_vew_apld_ico"><svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M22 12C22 17.52 17.52 22 12 22C6.48 22 2 17.52 2 12C2 6.48 6.48 2 12 2C17.52 2 22 6.48 22 12Z" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/><path class="icon_main" d="M15.7099 15.1798L12.6099 13.3298C12.0699 13.0098 11.6299 12.2398 11.6299 11.6098V7.50977" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/></svg> <span class="ajax-time" title="<?php echo date('c',$wo['job_apply']['time']); ?>"><?php echo Wo_Time_Elapsed_String($wo['job_apply']['time']); ?></span></p>
						</div>
					</div>
					<div class="row">
						<?php if (!empty($wo['job_apply']['phone_number'])) { ?>
							<div class="col-md-5">
								<p class="wo_vew_apld_ico"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M22 16.92v3a2 2 0 0 1-2.18 2 19.79 19.79 0 0 1-8.63-3.07 19.5 19.5 0 0 1-6-6 19.79 19.79 0 0 1-3.07-8.67A2 2 0 0 1 4.11 2h3a2 2 0 0 1 2 1.72 12.84 12.84 0 0 0 .7 2.81 2 2 0 0 1-.45 2.11L8.09 9.91a16 16 0 0 0 6 6l1.27-1.27a2 2 0 0 1 2.11-.45 12.84 12.84 0 0 0 2.81.7A2 2 0 0 1 22 16.92z"></path></svg> <?php echo $wo['job_apply']['phone_number']; ?></p>
							</div>
						<?php } ?>
						<?php if (!empty($wo['job_apply']['email'])) { ?>
							<div class="col-md-7">
								<p class="wo_vew_apld_ico"><svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M17 20.5H7C4 20.5 2 19 2 15.5V8.5C2 5 4 3.5 7 3.5H17C20 3.5 22 5 22 8.5V15.5C22 19 20 20.5 17 20.5Z" stroke="currentColor" stroke-width="2" stroke-miterlimit="10" stroke-linecap="round" stroke-linejoin="round"/><path class="icon_main" d="M17 9L13.87 11.5C12.84 12.32 11.15 12.32 10.12 11.5L7 9" stroke-width="2" stroke-miterlimit="10" stroke-linecap="round" stroke-linejoin="round"/></svg> <?php echo $wo['job_apply']['email']; ?></p>
							</div>
						<?php } ?>
					</div>
					<?php if ($wo['loggedin'] == true) { ?>
						<div class="wo_vew_apld_msg">
							<?php if (!empty($wo['page_profile'])) { ?>
								<button type="button" class="btn btn-main" onclick="Wo_OpenChatTab(0,0,0,<?php echo $wo['page_profile']['page_id']; ?>,<?php echo $wo['job_apply']['user_data']['user_id']; ?>)"><?php echo $wo['lang']['message'] ?></button>
							<?php }else{ ?>
								<button type="button" class="btn btn-main" onclick="Wo_OpenChatTab(<?php echo $wo['user_profile']['user_id']; ?>)"><?php echo $wo['lang']['message'] ?></button>
							<?php } ?>
						</div>
					<?php } ?>
				</div>
			</div>
			<div class="wo_vew_apld_blocks">
				<?php if (!empty($wo['job_apply']['where_did_you_work'])) { ?>
					<div class="wo_vew_apld_blkmrgn">
						<b><?php echo $wo['lang']['where_did_you_work']; ?></b>
						<p class="edited_text"><?php echo $wo['job_apply']['where_did_you_work']; ?></p>
					</div>
				<?php } ?>
				<div class="row">
					<div class="col-md-7">
					<?php if (!empty($wo['job_apply']['position'])) { ?>
						<div class="wo_vew_apld_blkmrgn">
							<b><?php echo $wo['lang']['position']; ?></b>
							<p class="edited_text"><?php echo $wo['job_apply']['position']; ?></p>
						</div>
					<?php } ?>
					</div>
					<div class="col-md-5">
						<div class="row">
							<div class="col-md-6">
								<?php if (!empty($wo['job_apply']['experience_start_date'])) { ?>
									<div class="wo_vew_apld_blkmrgn">
										<b><?php echo $wo['lang']['start_date']; ?></b>
										<p class="edited_text"><?php echo $wo['job_apply']['experience_start_date']; ?></p>
									</div>
								<?php } ?>
							</div>
							<div class="col-md-6">
								<?php if (!empty($wo['job_apply']['experience_end_date'])) { ?>
									<div class="wo_vew_apld_blkmrgn">
										<b><?php echo $wo['lang']['end_date']; ?></b>
										<p class="edited_text"><?php echo $wo['job_apply']['experience_end_date']; ?></p>
									</div>
								<?php } ?>
							</div>
						</div>
					</div>
				</div>
				<?php if (!empty($wo['job_apply']['experience_description'])) { ?>
					<div>
						<b><?php echo $wo['lang']['description']; ?></b>
						<p class="edited_text"><?php echo $wo['job_apply']['experience_description']; ?></p>
					</div>
				<?php } ?>
			</div>
			<div class="wo_vew_apld_blocks">
				<?php if (!empty($wo['job_apply']['question_one_answer']) && !empty($wo['job_apply']['job_info']['question_one'])) { ?>
					<div class="wo_vew_apld_blkmrgn">
						<b><?php echo $wo['job_apply']['job_info']['question_one']; ?></b>
						<?php if ($wo['job_apply']['job_info']['question_one_type'] == 'multiple_choice_question') { ?>
							<p class="edited_text"><?php echo $wo['job_apply']['job_info']['question_one_answers'][$wo['job_apply']['question_one_answer']]; ?></p>
						<?php  } else{ ?>
							<p class="edited_text"><?php echo $wo['job_apply']['question_one_answer']; ?></p>
						<?php  } ?>
					</div>
				<?php } ?>
				<?php if (!empty($wo['job_apply']['question_two_answer']) && !empty($wo['job_apply']['job_info']['question_two'])) { ?>
					<div class="wo_vew_apld_blkmrgn">
						<b><?php echo $wo['job_apply']['job_info']['question_two']; ?></b>
						<?php if ($wo['job_apply']['job_info']['question_two_type'] == 'multiple_choice_question') { ?>
							<p class="edited_text"><?php echo $wo['job_apply']['job_info']['question_two_answers'][$wo['job_apply']['question_two_answer']]; ?></p>
						<?php  } else{ ?>
							<p class="edited_text"><?php echo $wo['job_apply']['question_two_answer']; ?></p>
						<?php  } ?>
					</div>
				<?php } ?>
				<?php if (!empty($wo['job_apply']['question_three_answer']) && !empty($wo['job_apply']['job_info']['question_three'])) { ?>
					<div>
						<b><?php echo $wo['job_apply']['job_info']['question_three']; ?></b>
						<?php if ($wo['job_apply']['job_info']['question_three_type'] == 'multiple_choice_question') { ?>
							<p class="edited_text"><?php echo $wo['job_apply']['job_info']['question_three_answers'][$wo['job_apply']['question_three_answer']]; ?></p>
						<?php  } else{ ?>
							<p class="edited_text"><?php echo $wo['job_apply']['question_three_answer']; ?></p>
						<?php  } ?>
					</div>
				<?php } ?>
			</div>
		</div>
	</div>
</div>